### PR TITLE
fix the cpu rt grappa

### PR DESCRIPTION
**Pull request by gtdeveloper5**
fix the cpu rt grappa after testing this afternoon.

### CODE REVIEW

**Comment by hansenms** [comment]
What was the problem here? This fix seems to include some automated CPU fallback as well, is that correct?

**Comment by hansenms** [comment]
@gtdeveloper5, can you explain what the problem was with the coefficients not updating?

**Comment by gtdeveloper5** [comment]
Still need more time to do more test. Current problem is found to be that cpu code passing the same unmixing_, instead of reallocating new memory. It causes some wired behavior.

**Comment by hansenms** [comment]
If you still need to do more testing, what is this PR for exactly?

**Pull request closed without merging**
