### PR TITLE
Implementation of BART wrapper Gadget

### PR DESCRIPTION
**Pull request by hansenms**
This commit combines multiple commits by Mahamadou Diakite and Michael S. Hansen.

### CODE REVIEW

**Comment by hansenms** [comment]
@bijoumd78 This should merge everything. Can you please verify that it works as you would expect. 

@xueh2 would you be willing to take a look through this.

**Comment by bijoumd78** [comment]
@hansenms Yes, it includes all the changes I have made today. I have yet to give you the new "meas_MID00049_out.h5" file generated from today run.

**Comment by hansenms** [comment]
I made a new one. Uploaded it and updated the data.txt file. I changed the number of iterations to 50 to get a reasonable recon time. Can you check it?

This email was written on a mobile device. Please excuse brevity and/or typos.




On Fri, Nov 4, 2016 at 9:47 PM -0400, "Mahamadou Diakite" <notifications@github.com> wrote:












@hansenms Yes, it includes all the changes I have made today. I have yet to give you the new "meas_MID00049_out.h5" file generated from today run.

**Comment by bijoumd78** [comment]
@hansenms Yes, I have noticed the change. Indeed it will reduce the recon time but it will also reduce the output image quality, but we can always choose another set of data if the images are not too appealing.

**Comment by hansenms** [comment]
@bijoumd78 problem is that the test case is a giant dataset and I don't want an integration test that takes 5 minutes to run. We can check this one in for now, but can you please create a test with a smaller dataset. We can check it in later.

**Comment by bijoumd78** [comment]
Yes, I will work on it.

**Pull request merged**
