### PR TITLE
add toolbox image; add some morphology functions

### PR DESCRIPTION
**Pull request by xueh2**
add toolbox image
add morphology.h/.cpp for some morphological functions
add an unit test case

### CODE REVIEW

**Comment by tsangild** [comment]
Consider using the usual cpu/gpu sub-folders to make it clear which platform the functions are implemented for.

**Comment by xueh2** [comment]
Add cpu subfolder.

**Comment by hansenms** [comment]
I'm not sure I understand the `isEightConnected`, seems a bit arbitrary?

**Comment by xueh2** [comment]
add more comments and change function parameter naming to follow conventions

**Pull request merged**
