### PR TITLE
Add mri core kspace filter

### PR DESCRIPTION
**Pull request by xueh2**
Add functions for kspace filter in mri core.

### CODE REVIEW

**Comment by hansenms** [comment]
This looks reasonable to me. Why is the filter type a string? and as far as I can see, it is not really predictable what will happen if an unsupported filter type is supplied, right?

**Comment by xueh2** [comment]
Add checks for invalid filter type.
The filter type is string to avoid add definitions for a filter type class.

**Comment by inati** [comment]
But why don't we define a filter type class with the derived classes for each type?  There would still be a base class which defines the methods that all filters should support.

**Comment by hansenms** [comment]
There are other ways than a class or a string. It could simply be an enum or something. The string stuff is just messy, but it is not a major big deal.

**Comment by hansenms** [comment]
Actually upon thinking about it. Why is it a goal to not have a class for each filter type?

**Comment by xueh2** [comment]
As discussed, the kspace filter is defined as enmu types.

**Comment by hansenms** [comment]
getKSpaceFilterNameFromType is no longer needed, right?

Also, why do the filter type enums start at 160?

**Comment by xueh2** [comment]
Removed the unused function and change the start value of enum to be 1024. This is to avoid all enum to start from zero.

**Comment by hansenms** [comment]
Why is it a goal that they not start from zero? And why 1024?

**Comment by xueh2** [comment]
It is better to have enum value ranges not overlapped. So some groups of enum starts ,e.g. 0; others, 256; then 512; then 1024 ...

**Comment by hansenms** [comment]
Why? What is the specific advantage? 

(and BTW, by choosing 1024, you have now guaranteed that these will overlap with the enums for our message ids)

**Comment by xueh2** [comment]
ok, changed the enum to start with 0.

**Pull request merged**
