### PR TITLE
removes dependency from coroutine

### LINKED ISSUE #1019: why dependency on boost:coroutine?
CMake files say we depend on `boost::coroutine` https://github.com/gadgetron/gadgetron/blob/d7073e9dc3afd8891232c0519ee8fa9eb11b3ab9/apps/storage/CMakeLists.txt#L8
https://github.com/gadgetron/gadgetron/blob/12ffc43debb9bad2e170713006d29dea78d966bf/CMakeLists.txt#L205-L209
but it doesn't seem to be used anywhere at all in the code. Does this really need to be here?

### PR DESCRIPTION
**Pull request by paskino**
closes #1019

### CODE REVIEW

**Comment by hansenms** [comment]
Nope, I guess it is used by the storage server:

```
[365/365] Linking CXX executable apps/gadgetron/gadgetron
FAILED: apps/gadgetron/gadgetron 
: && /usr/bin/c++  -fopenmp -Werror=return-type -Werror=terminate -Werror=non-virtual-dtor -Werror=format-overflow -O3 -DNDEBUG   apps/gadgetron/CMakeFiles/gadgetron.dir/main.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/Server.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/Connection.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/initialization.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/system_info.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/config/Config.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/ConfigConnection.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/StreamConnection.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/Handlers.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/Writers.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/VoidConnection.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/HeaderConnection.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/Loader.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/Core.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/SocketStreamBuf.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/Stream.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/Parallel.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/Distributed.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/External.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/common/ExternalChannel.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/external/Matlab.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/external/Python.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/common/Discovery.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/ParallelProcess.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/PureStream.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/PureDistributed.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/common/External.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/common/Serialization.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/common/Configuration.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/distributed/Worker.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/nodes/distributed/Pool.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/connection/core/Processable.cpp.o apps/gadgetron/CMakeFiles/gadgetron.dir/storage.cpp.o  -o apps/gadgetron/gadgetron  -Wl,-rpath,/opt/code/gadgetron/build/gadgets:/opt/code/gadgetron/build/gadgets/plplot:/opt/code/gadgetron/build/gadgets/moco:/opt/code/gadgetron/build/gadgets/cartesian:/opt/code/gadgetron/build/gadgets/grappa:/opt/code/gadgetron/build/gadgets/spiral:/opt/code/gadgetron/build/gadgets/mri_noncartesian:/opt/code/gadgetron/build/gadgets/fatwater:/opt/code/gadgetron/build/gadgets/epi:/opt/code/gadgetron/build/gadgets/cmr:/opt/code/gadgetron/build/gadgets/interventional_mri:/opt/code/gadgetron/build/gadgets/mri_core:/opt/code/gadgetron/build/toolboxes:/opt/code/gadgetron/build/toolboxes/plplot:/opt/code/gadgetron/build/toolboxes/python:/opt/code/gadgetron/build/toolboxes/image_io:/opt/code/gadgetron/build/toolboxes/denoise:/opt/code/gadgetron/build/toolboxes/pattern_recognition:/opt/code/gadgetron/build/toolboxes/image:/opt/code/gadgetron/build/toolboxes/image/cpu:/opt/code/gadgetron/build/toolboxes/ffd:/opt/code/gadgetron/build/toolboxes/registration:/opt/code/gadgetron/build/toolboxes/registration/optical_flow:/opt/code/gadgetron/build/toolboxes/registration/optical_flow/cpu:/opt/code/gadgetron/build/toolboxes/dwt:/opt/code/gadgetron/build/toolboxes/dwt/cpu:/opt/code/gadgetron/build/toolboxes/nfft:/opt/code/gadgetron/build/toolboxes/nfft/cpu:/opt/code/gadgetron/build/toolboxes/deblur:/opt/code/gadgetron/build/toolboxes/fatwater:/opt/code/gadgetron/build/toolboxes/klt:/opt/code/gadgetron/build/toolboxes/klt/cpu:/opt/code/gadgetron/build/toolboxes/mri_image:/opt/code/gadgetron/build/toolboxes/cmr:/opt/code/gadgetron/build/toolboxes/mri:/opt/code/gadgetron/build/toolboxes/mri/epi:/opt/code/gadgetron/build/toolboxes/mri/spiral:/opt/code/gadgetron/build/toolboxes/mri/pmri:/opt/code/gadgetron/build/toolboxes/mri_core:/opt/code/gadgetron/build/toolboxes/core:/opt/code/gadgetron/build/toolboxes/core/cpu:/opt/code/gadgetron/build/toolboxes/core/cpu/hostutils:/opt/code/gadgetron/build/toolboxes/core/cpu/math:/opt/code/gadgetron/build/toolboxes/fft:/opt/code/gadgetron/build/toolboxes/fft/cpu:/opt/code/gadgetron/build/toolboxes/solvers:/opt/code/gadgetron/build/toolboxes/solvers/cpu:/opt/code/gadgetron/build/toolboxes/operators:/opt/code/gadgetron/build/toolboxes/operators/cpu:/opt/code/gadgetron/build/toolboxes/log:/opt/code/gadgetron/build/core:/opt/code/gadgetron/build/core/distributed:/opt/code/gadgetron/build/core/parallel:/opt/code/gadgetron/build/core/writers:/opt/code/gadgetron/build/core/readers:/usr/local/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial:  apps/storage/libgadgetron_storage.a  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0  -ldl  core/libgadgetron_core.so.4.1.2  toolboxes/core/cpu/libgadgetron_toolbox_cpucore.so.4.1.2  toolboxes/log/libgadgetron_toolbox_log.so.4.1.2  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/local/lib/libismrmrd.so.1.5.0  /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so  /usr/lib/x86_64-linux-gnu/libpthread.so  /usr/lib/x86_64-linux-gnu/libsz.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libdl.so  -lm  /usr/lib/librocksdb.so  /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.71.0  /usr/lib/x86_64-linux-gnu/libopenblas.so  -llapacke  /usr/lib/x86_64-linux-gnu/liblapacke.so && :
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::strand<boost::asio::io_context::executor_type> >, Gadgetron::Storage::StorageServer::StorageServer(unsigned short, boost::filesystem::path const&, boost::filesystem::path const&)::{lambda()#1}::operator()() const::{lambda(auto:1)#1}>&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> >::destroy()':
StorageServer.cpp:(.text+0xd23): undefined reference to `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::strand<boost::asio::executor> >, Gadgetron::Storage::REST::navi<Gadgetron::Storage::REST::RESTEndpoints<(anonymous namespace)::InfoEndPoint, (anonymous namespace)::BlobStorageEndPoint, (anonymous namespace)::BlobRetrievalEndPoint, (anonymous namespace)::WriteRequestEndPoint, (anonymous namespace)::DataInfoEndPoint> >(boost::asio::io_context&, boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>, Gadgetron::Storage::REST::RESTEndpoints<(anonymous namespace)::InfoEndPoint, (anonymous namespace)::BlobStorageEndPoint, (anonymous namespace)::BlobRetrievalEndPoint, (anonymous namespace)::WriteRequestEndPoint, (anonymous namespace)::DataInfoEndPoint>&, std::promise<unsigned short>&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >)::{lambda(auto:1)#1}>&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> >::destroy()':
StorageServer.cpp:(.text+0xde3): undefined reference to `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `boost::asio::detail::spawn_helper<boost::asio::executor_binder<void (*)(), boost::asio::strand<boost::asio::io_context::executor_type> >, Gadgetron::Storage::StorageServer::StorageServer(unsigned short, boost::filesystem::path const&, boost::filesystem::path const&)::{lambda()#1}::operator()() const::{lambda(auto:1)#1}>::operator()()':
StorageServer.cpp:(.text+0x1f80): undefined reference to `boost::coroutines::detail::coroutine_context::coroutine_context()'
/usr/bin/ld: StorageServer.cpp:(.text+0x1f94): undefined reference to `boost::coroutines::detail::coroutine_context::coroutine_context(void (*)(boost::context::detail::transfer_t), boost::coroutines::detail::preallocated const&)'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `boost::asio::detail::spawn_helper<boost::asio::executor_binder<void (*)(), boost::asio::strand<boost::asio::executor> >, Gadgetron::Storage::REST::navi<Gadgetron::Storage::REST::RESTEndpoints<(anonymous namespace)::InfoEndPoint, (anonymous namespace)::BlobStorageEndPoint, (anonymous namespace)::BlobRetrievalEndPoint, (anonymous namespace)::WriteRequestEndPoint, (anonymous namespace)::DataInfoEndPoint> >(boost::asio::io_context&, boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>, Gadgetron::Storage::REST::RESTEndpoints<(anonymous namespace)::InfoEndPoint, (anonymous namespace)::BlobStorageEndPoint, (anonymous namespace)::BlobRetrievalEndPoint, (anonymous namespace)::WriteRequestEndPoint, (anonymous namespace)::DataInfoEndPoint>&, std::promise<unsigned short>&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >)::{lambda(auto:1)#1}>::operator()()':
StorageServer.cpp:(.text+0x22e0): undefined reference to `boost::coroutines::detail::coroutine_context::coroutine_context()'
/usr/bin/ld: StorageServer.cpp:(.text+0x22f4): undefined reference to `boost::coroutines::detail::coroutine_context::coroutine_context(void (*)(boost::context::detail::transfer_t), boost::coroutines::detail::preallocated const&)'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `Gadgetron::Storage::StorageServer::StorageServer(unsigned short, boost::filesystem::path const&, boost::filesystem::path const&)::{lambda()#1}::operator()() const':
StorageServer.cpp:(.text+0x3aab): undefined reference to `boost::coroutines::stack_traits::default_size()'
/usr/bin/ld: StorageServer.cpp:(.text+0x3b76): undefined reference to `boost::coroutines::stack_traits::default_size()'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::strand<boost::asio::io_context::executor_type> >, Gadgetron::Storage::StorageServer::StorageServer(unsigned short, boost::filesystem::path const&, boost::filesystem::path const&)::{lambda()#1}::operator()() const::{lambda(auto:1)#1}>&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> >::run()':
StorageServer.cpp:(.text+0x52ac): undefined reference to `boost::coroutines::stack_traits::default_size()'
/usr/bin/ld: StorageServer.cpp:(.text+0x53c6): undefined reference to `boost::coroutines::stack_traits::default_size()'
/usr/bin/ld: StorageServer.cpp:(.text+0x5980): undefined reference to `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)'
/usr/bin/ld: StorageServer.cpp:(.text+0x5a34): undefined reference to `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `void boost::coroutines::detail::trampoline_push_void<boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::strand<boost::asio::executor> >, Gadgetron::Storage::REST::navi<Gadgetron::Storage::REST::RESTEndpoints<(anonymous namespace)::InfoEndPoint, (anonymous namespace)::BlobStorageEndPoint, (anonymous namespace)::BlobRetrievalEndPoint, (anonymous namespace)::WriteRequestEndPoint, (anonymous namespace)::DataInfoEndPoint> >(boost::asio::io_context&, boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>, Gadgetron::Storage::REST::RESTEndpoints<(anonymous namespace)::InfoEndPoint, (anonymous namespace)::BlobStorageEndPoint, (anonymous namespace)::BlobRetrievalEndPoint, (anonymous namespace)::WriteRequestEndPoint, (anonymous namespace)::DataInfoEndPoint>&, std::promise<unsigned short>&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >)::{lambda(auto:1)#1}>&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> > >(boost::context::detail::transfer_t)':
StorageServer.cpp:(.text+0xbc87): undefined reference to `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `boost::coroutines::detail::push_coroutine_impl<void>::push()':
StorageServer.cpp:(.text._ZN5boost10coroutines6detail19push_coroutine_implIvE4pushEv[_ZN5boost10coroutines6detail19push_coroutine_implIvE4pushEv]+0x35): undefined reference to `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)'
/usr/bin/ld: apps/storage/libgadgetron_storage.a(StorageServer.cpp.o): in function `boost::asio::detail::coro_async_result<boost::asio::executor_binder<void (*)(), boost::asio::executor>, unsigned long>::get()':
StorageServer.cpp:(.text._ZN5boost4asio6detail17coro_async_resultINS0_15executor_binderIPFvvENS0_8executorEEEmE3getEv[_ZN5boost4asio6detail17coro_async_resultINS0_15executor_binderIPFvvENS0_8executorEEEmE3getEv]+0x90): undefined reference to `boost::coroutines::detail::coroutine_context::jump(boost::coroutines::detail::coroutine_context&, void*)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

This storage server may be going away (being replaced with an external standalone), which would remove this (and a few other) dependencies.

@dchansen @kristofferknudsen

**Comment by KrisThielemans** [comment]
ok. Looks like it is optionally used by `asio` https://www.boost.org/doc/libs/1_76_0/doc/html/boost_asio/using.html. Apologies.

**Comment by KrisThielemans** [comment]
Would it be ok to create a PR to make the `apps/storage_server` optional for now? As far as I know, we don't need use it. To get that going, we need `RocksDB` as well (and a number of other things).

**Comment by dchansen** [comment]
The coroutine library is used in the storage server with Boost Beast, as it makes the code much shorter and easier to reason about.
However, we're actually in the process of moving the storage server out of Gadgetron, and into its own component, as part of (ISMR)MRD. 
When that work is finished, RocksDB and Coroutine should stop being dependencies. However, we will effectively have a dependency on Go (the language).

The noise prewhitening in Gadgetron requires the storage server to function, and that is a fairly central component in most reconstruction chains. As it is, we can't really make it optional. 

Could you help me unbderstand why it's an issue for you? Maybe we can find another solution.

**Comment by KrisThielemans** [comment]
thanks @dchansen It isn't a major issue. We're just trying to minimise dependencies as much as possible for SIRF. We find that dependency (conflict) management is taking up for too large a fraction of our time...

Feel free to close this PR and associated issue.

**Comment by paskino** [comment]
BTW how do you guys install RocksDB?

**Comment by dchansen** [comment]
@KrisThielemans That is absolutely fair.  Dependencies are quite a problem for us as well. We would have full windows support if we had a reliable way of providing LAPACKE.

In general, our policy (for C++) is to only have things that are available in the Ubuntu package manager, and preferably in VCPKG as well. 
We have debated auto-building Gadgetron deb packages for Ubuntu 20.04. Would that help you guys? Or do you prefer to stay on the SuperBuild path?

@paskino Through the package manager on Ubuntu and Fedora, and VCPKG on Windows.

**Comment by paskino** [comment]
Thanks @dchansen . I could not find where you install the `librocksdb-dev`.

**Comment by hansenms** [comment]
@dchansen, I don't think we will need to have golang as an explicit dependency in the Gadgetron repo since the storage server can be pulled as a static binary. If you prefer to have the option to compile the storage server in the Gadgetron build, we could have it conditional....if you have go, build, otherwise pull static binary. But I don't see a major advantage of doing that.

**Pull request closed without merging**
