### PR TITLE
fix ut test; add poly fit function; fix plplot finding etc.

### PR DESCRIPTION
**Pull request by xueh2**
. fix run_gadgetron_test.py
. install cmake files for packages depended on gadgetron
. add polyfit2 functions
. extend the [GenericImageReconGadget.h](https://github.com/gadgetron/gadgetron/compare/fix_run_gadgetron_test?expand=1#diff-ad5707f1bd551df46ea891a18f21695375a1b81150a498f1da428f0795450d30) to handle waveform

### CODE REVIEW

**Comment by hansenms** [comment]
@ahsanjav the merge to master you did is leaving this broken. Any chance you could have a look?

**Comment by ahsanjav** [comment]
> @ahsanjav the merge to master you did is leaving this broken. Any chance you could have a look?

Which merge the most recent one ? @hansenms

**Comment by hansenms** [comment]
> > @ahsanjav the merge to master you did is leaving this broken. Any chance you could have a look?
> 
> Which merge the most recent one ? @hansenms

image

**Comment by ahsanjav** [comment]
> > > @ahsanjav the merge to master you did is leaving this broken. Any chance you could have a look?
> > 
> > 
> > Which merge the most recent one ? @hansenms
> 
> image
Screenshot 2024-06-12 at 6 21 41 PM

I'll dig in - this should not break the tests. It passed all the tests when we originally merged the request. I'll test again and report back.

**Comment by hansenms** [comment]
I think this is an error that doesn't always occur, but I can repro it locally in the devcontainer.

**Pull request closed without merging**
