### PR TITLE
Fixed compilation on windows

### PR DESCRIPTION
**Pull request by dchansen**
This pull request adds a couple of cmake changes which fixes some Windows nonconformance issues.

### CODE REVIEW

**Comment by xueh2** [comment]
I am trying to repeat this. How did you install vcpkg? How to run the cmake?

**Comment by xueh2** [comment]
Hi David, I did the test. It solved many problems, but still have add fixes:

image

**Comment by xueh2** [comment]
And, still has a linking error:

2>------ Build started: Project: test_all, Configuration: Release x64 ------
2>cl : command line warning D9025: overriding '/openmp' with '/openmp:experimental'
2>hoSDC_test.cpp
2>hoSDC_test.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class std::shared_ptr<class Gadgetron::hoNDArray<float> > __cdecl Gadgetron::estimate_dcw<class Gadgetron::hoNDArray,float,2>(class Gadgetron::hoNDArray<class Gadgetron::vector_td<float,2> > const &,class Gadgetron::vector_td<unsigned __int64,2> const &,float,unsigned int)" (__imp_??$estimate_dcw@VhoNDArray@Gadgetron@@M$01@Gadgetron@@YA?AV?$shared_ptr@V?$hoNDArray@M@Gadgetron@@@std@@AEBV?$hoNDArray@V?$vector_td@M$01@Gadgetron@@@0@AEBV?$vector_td@_K$01@0@MI@Z) referenced in function "private: virtual void __cdecl hoSDC_test_randomTestOne_Test<float>::TestBody(void)" (?TestBody@?$hoSDC_test_randomTestOne_Test@M@@EEAAXXZ)
2>D:\gtuser\mrprogs\compiling\gadgetron_master_VC16_no_gpu\test\Release\test_all.exe : fatal error LNK1120: 1 unresolved externals
2>Done building project "test_all.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 22 up-to-date, 0 skipped ==========

**Comment by xueh2** [comment]
found the linking problem is due to:

/**
 * \file mri_sdc_export.h
 * \brief Export definitions for sampling density compensation.
 */

#ifndef MRI_SDC_EXPORT_H_
#define MRI_SDC_EXPORT_H_

#if defined (WIN32)
    #if defined(__BUILD_GADGETRON_CPUSDC__) <-- this line was incorrect
        #define EXPORTSDC __declspec(dllexport)
    #else
        #define EXPORTSDC __declspec(dllimport)
    #endif
#else
    #define EXPORTSDC
#endif

#endif  // MRI_SDC_EXPORT_H_

**Review by xueh2 — CHANGES_REQUESTED** [review]
find three other changes needed to get it fully compiled in windows

**Comment by dchansen** [comment]
Current commit compiles and runs on Windows with CUDA and vcpkg.
You shouldn't run CMake yourself, but instead use the CMake integration in visual studio.

**Comment by xueh2** [comment]
Hi David,

But the purpose is to get the windows compilation free of "mouse click" ... I am trying to make everything streamlined and reproducible.  It is better if we can do away with UI of visual studio, but rely on its compiler.

Why not merge current branch and I can test again.

Hui

**Review by xueh2 — APPROVED** [review]

**Comment by dchansen** [comment]
Will merge as soon as the CI passes

**Pull request merged**
