### PR TITLE
Dockerfile improvements

### PR DESCRIPTION
**Pull request by hansenms**
This PR removes the base images for the Docker images and reintroduces the `.devcontainer` based on the existing Dockerfile. Also cleaned up a bunch of old scripts that are no longer in use.

### CODE REVIEW

**Comment by hansenms** [comment]
@dchansen @kristofferknudsen @xueh2 

I have just put this up as a draft for now. It works in principle, but one problem is that the github workflow runs out of disk space when building the CUDA image from scratch:

```
Error processing tar file(exit status 1): write /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so: no space left on device
```

I will think about solutions, but for now:

* @dchansen was it something like this you had in mind when saying to eliminate base images?
* @xueh2 I am not sure what the status is on using chroot images, but it definitely would not work regardless with the 20.04 stuff being the only image, so I yanked it out. Thoughts?

**Comment by xueh2** [comment]
ok, I tested chroot built with 20.04 and it did not work on Mars. So we shall stop support mars chroot.

**Comment by hansenms** [comment]
@xueh2 I was trying to raise some questions around the Docker strategy in https://github.com/gadgetron/gadgetron/issues/901 but I think there is a broader issue here. At some point some things (like librange) were added and I think 18.04 stopped being able to build from then on (could be wrong about this, but I could not make it work). There does not appear to be any kind of testing done when stuff is checked into the repo, so I think it would make sense to have a discussion and decide:

1. What is supposed to work (like do we need chroot or is there a different strategy that could work on MARS)?
2. How do we get testing set up so that those things don't break.

At the moment there is really no image where all unit tests and integration tests pass. Even the 20.04 image has some issues...it may build, but tests certainly don't pass. It does not compile on 18.04. And 16.04 is long gone.

Is it supposed to work on MARS? Is chroot the only way? How, when, and by whom is it decided what the targets actually are?

I think it is somewhat urgent to establish some kind of continuous testing of all PRs on this project.

**Comment by dchansen** [comment]
@hansenms Policy for what *should* work is the latest Ubuntu LTS, as well as what is needed for clinical deployment. 
As we don't have any MARS systems available for testing, the last part is very hard for us to test. The MARS systems run across a number of Ubuntu versions, and have a number of peculiarities on top, such as not supporting IPv6. 

@kspaceKelvin Do you have any insight here? How many people are actually using Gadgetron under chroot? What would it take to support it? We could make an image that takes in almost everything from source (including gcc I guess) and builds it that way. 


@hansenms  You're right that testing is an issue, and has been as long as I've been part of the project. The main problem is that we need a beefy (~32Gb Memory, 8x CPU cores, an NVidia GPU) machine to run the tests. This machine needs to be maintained, have unrestricted internet access, not be turned off, etc. It's a time/money problem. 
Additionally, it's a real issue that there is a significant barrier to adding new integration tests, simply because getting the data up is cumbersome. 
Suggestions are welcome!

**Comment by hansenms** [comment]
@dchansen I’m meeting with @xueh2 later today and will forward the invite to you in case you are able to join.

**Comment by dchansen** [comment]
@hansenms  This pull request builds the docker images, but do not push them anywhere as far as I can tell. Can we reintroduce that?

**Comment by hansenms** [comment]
@dchansen yes, adding the push back in. Just have to work my way through the syntax.

**Review by xueh2 — APPROVED** [review]

**Pull request merged**
