### PR TITLE
add work-around for Numpy 1.6 compatibility

### PR DESCRIPTION
**Pull request by KrisThielemans**
This patch allows compilation with Numpy 1.6.

### CODE REVIEW

**Comment by hansenms** [comment]
@KrisThielemans, thanks for this suggestion, however, I am not sure that we generally support numpy 1.6. It is certainly not being tested. So could you help me understand a bit what platform you are on, what conditions this is being compiled under and whether all tests pass with numpy 1.6?

This particular change would have no effect on numpy > 1.6 but putting it in would sort of imply that we are supporting that, which I am not sure that we do. Also the typical system that would have that installed would not be supported, so I just want to make sure that I understand this correctly.

**Comment by KrisThielemans** [comment]
yes. I guessed you didn't support numpy 1.6. However, it solved my problem with getting Gadgetron to compile on Ubuntu 12.04, Python 2.7, using gcc-5.2.1
> $ uname -a
> Linux INM304 3.2.0-70-generic #105-Ubuntu SMP Wed Sep 24 19:49:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I'll confess I'm not 100% sure how to execute all tests (sorry, I should have checked the doc). "make test" didn't do anything (which surprised me). build/test/test_all reports
> [----------] Global test environment tear-down
> [==========] 232 tests from 34 test cases ran. (10716 ms total)
> [  PASSED  ] 232 tests.

Anything else I should try?

**Comment by hansenms** [comment]
I suspect you made it compile, but I seriously doubt that it would run. But let's see if we can work it out. Stay with me here, it make take a few tries. 

First of all, could you post your output of:

    gadgetron_info

 Make sure you have the following packages installed:

https://github.com/ismrmrd/ismrmrd-python
https://github.com/ismrmrd/ismrmrd-python-tools
https://github.com/ismrmrd/siemens_to_ismrmrd

Then:

Copy `$GADGETRON_HOME/share/gadgetron/config/gadgetron.xml.example` to `$GADGETRON_HOME/share/gadgetron/config/gadgetron.xml` (I suspect you would have done that already)

Fetch Gadgetron test data, run 

    python get_data.py

in `test/integration` in the Gadgetron source tree.

Downloading all this data will take a while and some times so long that it hangs and needs to be restarted, but it should eventually work.

Run integration tests: run 

    python run_all_tests.py test_cases.txt 

in `test/integration` in the Gadgetron source tree.

Let me know how that goes.

**Comment by KrisThielemans** [comment]
that gives me a probably unrelated error,
>$ python run_all_tests.py test_cases.txt
>Grabbing test case: cases/gtplus_localizer.cfg
>Traceback (most recent call last):
>  File "run_all_tests.py", line 72, in <module>
>   sys.exit(main())
 > File "run_all_tests.py", line 44, in main
>   r = subprocess.call(["python", "run_gadgetron_test.py", "-I", ismrmrd_home, "-G", >gadgetron_home, t, "-a", str(args.address), "-p", str(args.port)])
>  File "/usr/lib/python2.7/subprocess.py", line 493, in call
>   return Popen(*popenargs, **kwargs).wait()
>  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
>    errread, errwrite)
>  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
>    raise child_exception
> TypeError: execv() arg 2 must contain only strings

**Comment by hansenms** [comment]
What are the values of your `ISMRMRD_HOME` and `GADGETRON_HOME` environment variables?

If they are not set, you need to provide these paths with `-I` and `-G` command line parameters. If you are installing at default locations, the values are `/usr/local` for both.

**Comment by KrisThielemans** [comment]
sorry... ok. that fixed that. The first few test cases run now fine until I get to cases/simple_gre_python.cfg. Checking gadgetron.log I find after a while

```
016-01-09 18:22:05 INFO [GadgetStreamController.cpp:343]   Gadget dll: gadgetron_python
2016-01-09 18:22:05 INFO [GadgetStreamController.cpp:344]   Gadget class: PythonGadget
ACE (5235|140110397949696) DLL_Handle::open - libgadgetron_python (-268317808), refcount=3
2016-01-09 18:22:05 INFO [GadgetStreamController.cpp:359]   Gadget parameters: 3
2016-01-09 18:22:05 INFO [GadgetStreamController.cpp:366] Setting parameter python_path = /home/myuser/scripts/python
2016-01-09 18:22:05 INFO [GadgetStreamController.cpp:366] Setting parameter python_module = remove_2x_oversampling
2016-01-09 18:22:05 INFO [GadgetStreamController.cpp:366] Setting parameter python_class = Remove2xOversampling
2016-01-09 18:22:05 INFO [GadgetStreamController.cpp:387] Gadget Stream configured
2016-01-09 18:22:05 DEBUG [PythonGadget.h:61] Python Path            : /home/myuser/scripts/python
2016-01-09 18:22:05 DEBUG [PythonGadget.h:62] Python Module          : remove_2x_oversampling
2016-01-09 18:22:05 DEBUG [PythonGadget.h:63] Python Class           : Remove2xOversampling
2016-01-09 18:22:05 DEBUG [PythonGadget.h:61] Python Path            : /home/myuser/scripts/python
2016-01-09 18:22:05 DEBUG [PythonGadget.h:62] Python Module          : accumulate_and_recon
2016-01-09 18:22:05 DEBUG [PythonGadget.h:63] Python Class           : AccumulateAndRecon
2016-01-09 18:22:05 ERROR [python_ismrmrd_converter.h:81] ImportError: No module named ismrmrd
2016-01-09 18:22:05 DEBUG [Gadget.h:247] Gadget::process() failed
 --> ImportError: No module named ismrmrd
2016-01-09 18:22:05 ERROR [Gadget.h:254] Gadget (RemoveOversamplingPython) process failed
2016-01-09 18:22:05 DEBUG [Gadget.h:174] Gadget (RemoveOversamplingPython) Close Called with flags = 0
2016-01-09 18:22:05 ERROR [GadgetStreamController.cpp:149] Failed to put stuff on stream, too long wait, 0
2016-01-09 18:22:05 DEBUG [GadgetStreamController.cpp:173] handle_close called
2016-01-09 18:22:05 INFO [GadgetStreamController.cpp:178] Shutting down stream and closing up shop...
2016-01-09 18:22:05 DEBUG [Gadget.h:174] Gadget (RemoveOversamplingPython) Close Called with flags = 1
2016-01-09 18:22:05 DEBUG [Gadget.h:181] Gadget (RemoveOversamplingPython) failed to put hang up message on queue
2016-01-09 18:22:05 DEBUG [Gadget.h:123] Shutting down Gadget (RemoveOversamplingPython)
2016-01-09 18:22:05 DEBUG [Gadget.h:174] Gadget (AccReconPython) Close Called with flags = 1
2016-01-09 18:22:05 DEBUG [Gadget.h:184] Gadget (AccReconPython) waiting for thread to finish
2016-01-09 18:22:05 DEBUG [PythonGadget.h:106] Error loading python modules in Gadget AccReconPython
Traceback (most recent call last):
  File "/usr/local/bin/..//share/gadgetron/python/accumulate_and_recon.py", line 4, in <module>
    import ismrmrd
ImportError: No module named ismrmrd
```
I cannot find such a module indeed. Am I missing something else? Sorry again.

**Comment by hansenms** [comment]
As mentioned above, please install:

https://github.com/ismrmrd/ismrmrd-python
https://github.com/ismrmrd/ismrmrd-python-tools

That is the Python API for ISMRMRD and a toolbox with some MRI recon stuff in Python. They are used by the Gadgets.

**Comment by KrisThielemans** [comment]
aargh. how could I miss installing ismrmrd-python then? Many thanks for your patience.

After fixing that, run_all_tests.py succeeds! (also the nosetests in ismrmrd-python/tests). I don't have a GPU in this system though.

Of course, I don't suggest you start to support Numpy 1.6 officially, or such an old Ubuntu system (nobody in their right mind should use Gadgetron in seriousness with this configuration, I just went this because it was the only linux system that I had available).

By the way, I forgot to mention in my configuration that I've had to use a recent boost download (1.60) as the Ubuntu 12.04 boost package was also too old.

PS: is this testing procedure documented anywhere? I don't seem to find any python info on the gadgetron wiki.

**Comment by hansenms** [comment]
OK, sounds like this PR is pretty benign, so I will merge it. 

There is some documentation of the integration tests but at the moment it is only in the Mac installation section, we should clean that up and separate out. Traditionally, these tests have been for people doing integration on new platforms, etc. And we use them in our continuous integration system, but we have not really advertised them widely since there are more dependencies that one needs in order to get it all working. We should probably type it up for people that are interested.

**Pull request merged**
