### PR TITLE
only look for Python 2 in FindPythonLibs

### PR DESCRIPTION
**Pull request by ghisvail**
If you are in a setup like me where you also have a development environment for Python 3, you can end-up in a situation where FindPythonInterp and FindPythonLibs provides inconsistent python versions, leading to build errors. The solution is to explicitly set the version of Python to be used (here Python 2).

Before
--------

In CMakeCache.txt
//Details about finding PythonInterp
FIND_PACKAGE_MESSAGE_DETAILS_PythonInterp:INTERNAL=[/usr/bin/python][v2.7.9()]
//Details about finding PythonLibs
FIND_PACKAGE_MESSAGE_DETAILS_PythonLibs:INTERNAL=[/usr/lib/x86_64-linux-gnu/libpython3.4m.so][/usr/include/python3.4m][v3.4.2()]

Build log:
Linking CXX executable gadgetron_test_python
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_Size'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyUnicodeUCS4_FromEncodedObject'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyFile_FromString'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_Type'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyInt_Type'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_FromString'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyUnicodeUCS4_AsWideChar'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_FromStringAndSize'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `Py_InitModule4_64'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_FromFormat'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyNumber_Divide'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyNumber_InPlaceDivide'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyInt_AsLong'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_InternFromString'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyClass_Type'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_AsString'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyInt_FromLong'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyFile_AsFile'
collect2: error: ld returned 1 exit status
toolboxes/python/example/CMakeFiles/gadgetron_test_python.dir/build.make:97: recipe for target 'toolboxes/python/example/gadgetron_test_python' failed
make[2]: *** [toolboxes/python/example/gadgetron_test_python] Error 1
CMakeFiles/Makefile2:1105: recipe for target 'toolboxes/python/example/CMakeFiles/gadgetron_test_python.dir/all' failed
make[1]: *** [toolboxes/python/example/CMakeFiles/gadgetron_test_python.dir/all] Error 2
Makefile:107: recipe for target 'all' failed
make: *** [all] Error 2

After
------

In CMakeCache.txt

//Details about finding PythonInterp
FIND_PACKAGE_MESSAGE_DETAILS_PythonInterp:INTERNAL=[/usr/bin/python][v2.7.9()]
//Details about finding PythonLibs
FIND_PACKAGE_MESSAGE_DETAILS_PythonLibs:INTERNAL=[/usr/lib/x86_64-linux-gnu/libpython2.7.so][/usr/include/python2.7][v2.7.9()]

The build is now successful.

### CODE REVIEW

**Comment by inati** [comment]
Does the code not compile properly with Python3?

It seems findPython is rather dumb.  Did you try helping it by passing the cmake Python variables at the command line?  I have to do this for Mac homebrew and windows with WinPython and any other non bog-standard configuration.

**Comment by naegelejd** [comment]
It depends on the Boost Python you have installed. Using homebrew for
example, boost-python is compiled against Python 2 by default
(--with-python3 is an option). I think this is a safe change until someone
complains about not being able to use Python 3 (because they are using
Boost-Python compiled against Python 3).

On another note: it may be worthwhile to vendor the `FindPythonXXX` cmake
scripts in Gadgetron like we do for so many others. This way I could patch
them up to actually find the right stuff on every system (Mac OS X
especially).

--
Joe Naegele
joseph.naegele@gmail.com
josephnaegele.com
301.676.1403

**Comment by ghisvail** [comment]
Same for Debian / Ubuntu. Boost python depends on the default Python
interpreter which is still Python 2.x.

**Comment by hansenms** [comment]
Well at least this way, it is the tested configuration that we support. Until we start testing with Python 3, it is probably pretty safe to keep it like this.

**Pull request merged**
