### PR TITLE
up

### PR DESCRIPTION
**Pull request by bijoumd78**

### CODE REVIEW

**Comment by siatjiasen** [comment]
Hi,

I am trying this bartgadget. Following is my results:
1. The "Sample_GRAPPA_Recon.txt" containing Bart commands is installed to /share/gadgetron/bart. But it may be better to be installed to /usr/local/share/gadgetron/bart.
I changed /gadgets/bart/Cmakelists.txt :  
set(GADGETRON_INSTALL_BART_PATH share/gadgetron/bart)
install (FILES Sample_GRAPPA_Recon.txt DESTINATION ${GADGETRON_INSTALL_BART_PATH})
Also bartgadget.cpp should be acknowledged where this file is located.

2. The file names of hdr/cfl written by bartgadget.cpp are different from file names given in Sample_GRAPPA_Recon.txt. 
bartgadget.cpp write kspace and acs data to "meas_gadgetron.cfl" and "meas_gadgetron_ref.cfl". But bart command in Sample_GRAPPA_Recon.txt use "reference_data" and "input_data".

3. The PrepRefGadget will cut the center full sampled kspace (integrated reference data). Thus the size of reference_data is smaller than full kspace size, give a coil sensitivity maps of size different from image size. Maybe the combination of "ecalib -1" and "ecaltwo sx sy sz" can help.

4.  Currently, bart commands are provided in a txt file. Will it be better to use a .sh file? Sometimes I get a wrong .hdr/.cfl name. For example, "maps.cfl" is desired, but it may be changed to "maps .cfl" (I forget space after maps before new line) Then the following bart command claims that "file can't be found".

This work is helpful to use. Thank you.
Best wishes,
Jia Sen

**Comment by siatjiasen** [comment]
Hi,

I have tried this bartgadget, and can do a 3D recon offline. Following is my results:
1. The "Sample_GRAPPA_Recon.txt" containing Bart commands was installed to /share/gadgetron/bart. But it may be better to be installed to /usr/local/share/gadgetron/bart.
I changed /gadgets/bart/Cmakelists.txt :

set(GADGETRON_INSTALL_BART_PATH share/gadgetron/bart)
install (FILES Sample_GRAPPA_Recon.txt DESTINATION ${GADGETRON_INSTALL_BART_PATH})
Also bartgadget.cpp should be acknowledged where this file is located.

2. Before Bart recon, the reference and kspace data are reshaped. 
cmd1 << "bart reshape 15 " << DIMS_ref[2] << " " << DIMS_ref[0] << " " << DIMS_ref[1] << " " << DIMS_ref[3] << " meas_gadgetron_ref meas_gadgetron_ref_reshape";
In my opinion, this will reshape the original data in the order of [RO, PE, PAR, CHA] to [PAR, RO, PE, CHA]. Why this reshape is required? 

3. Currently, bart commands are provided in a txt file. Is it possible to use a .sh file, and run the shell script directly?

4. I found that bartgadget could not be integrated with Generic Recon Gadgets such as Partial Fourier Handling, k-space filtering, etc. Is there any plan to make the bart gadget to use GenericReconGadget as the base class?  

Thank you very much.
Best wishes,
Jia Sen

**Comment by hansenms** [comment]
@siatjiasen we are working on some of the issues that you raise. @bijoumd78 I think you should close this PR for now and put up an updated one when ready.

**Comment by bijoumd78** [comment]
Hi Jia,
Thanks for running bart gadget. This is a work in progress which makes your
feedback valuable for making the gadget better. Thanks again, and keep
sending us more suggestions, we will do our best to implement any feasible
improvement.
With that out the way,here are the answers to some of the questions that
you have raised.

1)   Before Bart recon, the reference and kspace data are reshaped.
cmd1 << "bart reshape 15 " << DIMS_ref[2] << " " << DIMS_ref[0] << " " <<
DIMS_ref[1] << " " << DIMS_ref[3] << " meas_gadgetron_ref
meas_gadgetron_ref_reshape";
In my opinion, this will reshape the original data in the order of [RO, PE,
PAR, CHA] to [PAR, RO, PE, CHA]. Why this reshape is required?

*The examples provided on the BART website always reshape the raw data in
the order [*PAR, RO, PE, CHA etc]* before applying any other algorithm. See
the examples on the bart website for further explanations. *

*2) *Currently, bart commands are provided in a txt file. Is it possible to
use a .sh file, and run the shell script directly?

We are looking into it.

3) I found that bartgadget could not be integrated with Generic Recon
Gadgets such as Partial Fourier Handling, k-space filtering, etc. Is there
any plan to make the bart gadget to use GenericReconGadget as the base
class?

That is a good point , stay tune for future update.

Thanks again for your prompt feedback, I really appreciate it!

Mahamadou.

**Pull request closed without merging**
