### PR TITLE
Epi correction: polynomial odd-even phase correction

### PR DESCRIPTION
**Pull request by pvelasco**
I have included a new option for the odd-even phase correction.  Currently, it does a linear fit to the phase difference between odd and even navigators; I have added a new option: to do a polynomial fit.  (I have hardcoded the order of the polynomial to be 4th order, but it can be changed.)  There is a gadget property to control the type of fit, but I have the polynomial as default, since I think it is better (see below).

The reason behind this is that when you do a linear fit and correct for it, the residual clearly has higher oder terms (it is not just random noise).  For example, the following figure shows the phase difference between odd and even navigators (after B0 correction), for one of the slices and repetitions of the epi_2d integration test dataset:

[odd-even_phase_diff_example.pdf](https://github.com/gadgetron/gadgetron/files/542778/odd-even_phase_diff_example.pdf)

In blue is the original phase difference: clearly linear; in red, is the residual, after the linear phase removal.  In the figure insert you see what happens when you expand the y-axis: there is a clear quadratic trend.

So it makes sense to do a polynomial fit.  However, instead of removing the linear fit in the complex domain and substitute it with a (robust) polynomial fit, I first do the linear fit in the complex domain and then do a robust polynomial fit of the residual.  The reason is that if the phase difference (blue line in the figure) wraps, the polynomial fit will try to fit the -pi,+pi phase jumps.  It doesn't happen in the test dataset, but I have seen it.

After fitting the residual to a polynomial and combine it with the initial linear fit, the phase difference between odd and even navigators is greatly reduced:

[odd-even_phase_diff_poly_fit_example.pdf](https://github.com/gadgetron/gadgetron/files/542790/odd-even_phase_diff_poly_fit_example.pdf)

In blue is the residual from the linear fit, and in red the residual after the polynomial fit.  (Note that the blue curve in this second figure is the same one plotted in red in the first figure).  The new residual is very much reduced, especially away from the center.

Now, when you do the image reconstruction using the linear fit (i.e., current version of the correction) and compare it to the images reconstructed using the polynomial fit (proposed correction) here is what you see:

For the epi_2d series.  Comparing the means across repetitions (windowed to highlight the ghosting):

meanb0_linearoephase_tmean
meanb0_polyoephase_tmean
oephase_tmean_linear_minus_poly
oephase_tmean_linear_minus_poly_colorbar

Top: using linear correction; middle: using polynomial correction; bottom, in color: difference linear-minus-polynomial (red-yellow: linear correction has higher mean; blue-lightblue: polinomial correction has higher mean).  In the difference image, note that most of the ghost is yellow, indicating that the linear correction gives more ghosting.

For the epi_2d series.  Comparing the standard deviation (stability) across repetitions:

meanb0_linearoephase_tstd
meanb0_polyoephase_tstd
oephase_tstd_linear_minus_poly
oephase_tstd_linear_minus_poly_colorbar
Top: using linear correction; middle: using polynomial correction; bottom, in color: difference linear-minus-polynomial (red-yellow: linear correction has higher temporal std; blue-lightblue: polinomial correction has higher temporal std).  In the difference image, note that most of the image is red-yellow, indicating that the linear correction is less stable.  I'm not sure why one of the slices has the polynomial correction as less stable.

Now, looking at the generic_grappa_epi_ave (single image, windowed to highlight the ghosting):
meanb0_linearoephase_grappa
meanb0_polyoephase_grappa

Top: using linear correction; bottom: using polynomial correction. Note the lower ghosting for the polynomial correction, especially in the middle slices.

(I'm including some matlab code to look at the navigator phase difference fits in a later comment).

### CODE REVIEW

**Comment by pvelasco** [comment]
Here is a link to the ref_20161020.h5 file:
https://drive.google.com/file/d/0B3Wx_3B2y_lZeXRMWXliWnF2TzQ/view?usp=sharing

Here is a link to the epi_2d_out_20161020_pjv.h5 file:
https://drive.google.com/file/d/0B3Wx_3B2y_lZVnJyUTMzWFYxOW8/view?usp=sharing

**Comment by pvelasco** [comment]
Here is the Matlab code to extract the navigators and compare the different fits to the odd-even phase differences.  You need to insert an ismrmrd_dump _before_ the EPICorrGadget:

```
<gadget>
  <name>IsmrmrdDump</name>
  <dll>gadgetron_mricore</dll>
  <classname>IsmrmrdDumpGadget</classname>
  <property><name>file_prefix</name><value>ISMRMRD_DUMP</value></property>
  <property><name>append_timestamp</name><value>1</value></property>
</gadget>
```

Then, in Matlab, get the data and extract just the navigators:

```
cd /Users/pvelasco/data/gadgetron/integration_test/Docker_test/

addpath ~/temp/ismrmrd/matlab/

clear
fName = 'ISMRMRD_DUMP_45160_88093439_88093444_517.h5';
dset = ismrmrd.Dataset(fName);

% read all acquisitions in the file:
acq = dset.readAcquisition();

% find how many lines are navigators:
nav_yes = acq.head.flagIsSet(acq.head.FLAGS.ACQ_IS_PHASECORR_DATA);
% to get the number of navigators per shot, just get the first
%   few acquisitions and look at how many navigators we have
%   before the first non-navigator line:
Nnavs = find( nav_yes==0, 1, 'first') - 1;

% Then, the number of shots would be total number of navigators
%   divided by the number of navigators (and rounded down):
Nshots = floor(sum(nav_yes)/Nnavs);

% get the number of slices look at the unique elements of the
%   slice index:
slices = unique( acq.head.idx.slice );
Nz = numel(slices);

% and the number of volumes:
Nt = floor(Nshots/Nz);

% Number of voxels along the RO:
Nx = size(acq.data{1},1);
% Number of coils:
Nc = size(acq.data{1},2);
% Echo-Train-Length:
ETL = numel(nav_yes)/Nshots - Nnavs;


%% First volume, including the navigators
% This volume has no phase encoding.

Vol1 = zeros(Nx, Nc, ETL, Nz);
n=1;
for zn=1:Nz
  for ky=1:ETL+Nnavs
    Vol1(:,:,ky,zn) = acq.data{n};
    n = n+1;
  end
end
N_after_1st_vol = n;


%% Remaining volumes:

Nt = floor(Nshots/Nz)-1;

% just keep the navigators and ky=0 line:

navdata_   = complex(zeros(Nx, Nc, Nnavs, Nz, Nt));
ky0        = complex(zeros(Nx, Nc, Nz, Nt));
% loop through all the lines of data and get the navigators:
n = N_after_1st_vol;
while (n<=numel(nav_yes))
  if nav_yes(n)==1
    % store Nnavs:
    for nav=1:Nnavs
      navdata_(:,:,nav,acq.head.idx.slice(n)+1,acq.head.idx.repetition(n)+1) = acq.data{n};
      n = n+1;
    end
  else
    if (acq.head.idx.kspace_encode_step_1(n) == ETL/2)
      ky0(:,:,acq.head.idx.slice(n)+1,acq.head.idx.repetition(n)+1) = acq.data{n};
    end
    % move to the next line:
    n = n+1;
  end
end

%% Get TE and Echo-Spacing:

hola = dset.readxml;

% From the header:
TE = 30;   % in ms
ES = 0.5;  % in ms


%% Time between navigators and EPI readout
%
% To compute the B0 correction, we need to get the time from the
% first navigator to the beginning of the EPI train

tstamps = acq.head.acquisition_time_stamp;
tstamps = reshape(tstamps,Nnavs+ETL,Nshots);

% average time between the second navigator and the ky=0 line,
%   in units of the time-stamps raster:
t_ky0_nav2_raster = mean(tstamps(Nnavs+ETL/2+1,:)-tstamps(2,:));

% now, to calculate the time-stamp raster:
% the time differences between readouts:
tstamps_diff = diff(tstamps);
% the mean echo spacing (exclude the time between the third nav and
%  the first EPI readout:
ES_raster = mean( mean( tstamps_diff([1:Nnavs-1,Nnavs+1:end],:) ) );

% since we know from the header the ES in ms, then the raster would be:
raster_in_ms = ES/ES_raster;

% rounding it to the first decimal place:
raster_in_ms = 0.1*round( 10*raster_in_ms );   % it is 2.5 ms, as expected :)

% then, in ms:
t_ky0_nav2_ms = t_ky0_nav2_raster * raster_in_ms;
% and in ES:
t_ky0_nav2 = t_ky0_nav2_ms / ES;

% so, to the beginning of the EPI train, we have to subtract ETL/2:
t_kymin_nav2 = t_ky0_nav2 - ETL/2;

%%

clear acq nav_yes dset

save(sprintf('%s_navdata_.mat',fName(1:end-3)));
```

Now, you can play with the navigator phase differences:

```
cd /Users/pvelasco/data/gadgetron/integration_test/Docker_test/

clear

fName = 'ISMRMRD_DUMP_45160_88093439_88093444_517.h5';
load( sprintf('%s_navdata_.mat',fName(1:end-3)) );

%%  First, compute the B0 correction  %%

x = linspace(-0.5,0.5,Nx)';

% Phase difference nav3-nav1:
ctemp = complex(zeros(Nx,Nz,Nt));
slope = zeros(Nz,Nt);
intercept = zeros(Nz,Nt);
corrB0 = complex(zeros(Nx,Nz,Nt));
for t=1:Nt
  for zn=1:Nz
    for p=1:(Nnavs-2)
      % combine across coils (and accumulate across triplets):
      ctemp(:,zn,t) = ctemp(:,zn,t) + squeeze(sum(conj(navdata_(:,:,p,zn,t)).*navdata_(:,:,p+2,zn,t),2));
    end
    slope(zn,t) = (Nx-1) * squeeze(angle( sum(conj(ctemp(1:end-1,zn,t)).*ctemp(2:end,zn,t)) ));
    ctemp(:,zn,t) = ctemp(:,zn,t) .* exp(-1i*slope(zn,t)*x);
    intercept(zn,t) = squeeze(angle(sum(ctemp(:,zn,t))));
    tvec = slope(zn,t)*x + intercept(zn,t);
    corrB0(:,zn,t) = exp(-1i*0.5*tvec);
  end
end



%% How do we calculate the Odd-Even phase difference?
% From nav2 to nav3 or to the average of nav1/nav3?

for t=1:Nt
  for zn=1:Nz
%   for zn=4
    % Plot nav1, nav3 and nav1+nav3:
    for p=1:(Nnavs-2)
      for c=1:Nc
        plot( squeeze(angle( [ navdata_(:,c,p  ,zn,t)./corrB0(:,zn,t) ...
                               navdata_(:,c,p+2,zn,t).*corrB0(:,zn,t) ...
                               navdata_(:,c,p  ,zn,t)./corrB0(:,zn,t) + navdata_(:,c,p+2,zn,t).*corrB0(:,zn,t)
                            ] ) ) )
        legend('nav1','nav3','mean')
        pause
      end
    end
  end  
end
```
You can see that taking the average of nav1 and nav3 gives you the average angle (more or less: there is a little bias towards nav1, since it has higher magnitude).

Now, let's take a look at what happens across coils:

```
for t=1:Nt
%   for zn=1:Nz
  for zn=4
    % Plot nav1, nav3 and nav1+nav3:
    for p=1:(Nnavs-2)
      % combine across coils (and accumulate across triplets):
        subplot(2,1,1)
        plot( squeeze(abs( navdata_(:,:,p+1,zn,t) ) ) )
        subplot(2,1,2)
        plot( squeeze(angle( [navdata_(:,:,p+1,zn,t) .* ...
                            conj(navdata_(:,:,p  ,zn,t).*repmat(1./corrB0(:,zn,t),1,Nc) + ...
                                 navdata_(:,:,p+2,zn,t).*repmat(corrB0(:,zn,t),1,Nc) )...
                            ] ) ) )
        hold on
        plot( squeeze(angle(sum( [navdata_(:,:,p+1,zn,t) .* ...
                            conj(navdata_(:,:,p  ,zn,t).*repmat(conj(corrB0(:,zn,t)),1,Nc) + ...
                                 navdata_(:,:,p+2,zn,t).*repmat(corrB0(:,zn,t),1,Nc) )...
                            ] ,2) ) ), 'LineWidth',10 )
        ylim(0.5*[-1 1])
        hold off
        pause
    end
  end  
end
\end{lstlisting}

You can see there is some significant differences in the phase difference from coil to coil.  But I guess that taking the average across coils makes sense.

\begin{lstlisting}
%% Compute odd-even correction:

ctemp = complex(zeros(Nx,Nz,Nt));
slope = zeros(Nz,Nt);
intercept = zeros(Nz,Nt);
corrpos = complex(zeros(Nx,Nz,Nt));
corrneg = complex(zeros(Nx,Nz,Nt));
ctemp_corr = complex(zeros(Nx,Nz,Nt));
for t=1:Nt
  for zn=1:Nz
%   for zn=4
    % Phase difference nav1/nav3 and nav2:
    for p=1:(Nnavs-2)
      % combine across coils (and accumulate across triplets):
      ctemp(:,zn,t) = ctemp(:,zn,t) + squeeze(sum( conj( navdata_(:,:,p  ,zn,t).*repmat(1./corrB0(:,zn,t),1,Nc) + ...
                                         navdata_(:,:,p+2,zn,t).*repmat(corrB0(:,zn,t),1,Nc) ) .* ...
                                   navdata_(:,:,p+1,zn,t) , 2 ));
    end
    slope(zn,t) = (Nx-1) * squeeze(angle( sum(conj(ctemp(1:end-1,zn,t)).*ctemp(2:end,zn,t)) ));
    pppp = ctemp(:,zn,t) .* exp(-1i*slope(zn,t)*x);
    intercept(zn,t) = squeeze(angle(sum(pppp)));
    tvec = slope(zn,t)*x + intercept(zn,t);
    corrpos(:,zn,t) = exp(-1i*0.5*tvec);
    corrneg(:,zn,t) = exp( 1i*0.5*tvec);
    for p=1:(Nnavs-2)
      % combine across coils (and accumulate across triplets):
      ctemp_corr(:,zn,t) = ctemp_corr(:,zn,t) + squeeze(sum( conj( navdata_(:,:,p  ,zn,t).*repmat(corrneg(:,zn,t)./corrB0(:,zn,t),1,Nc) + ...
                                         navdata_(:,:,p+2,zn,t).*repmat(corrneg(:,zn,t).*corrB0(:,zn,t),1,Nc) ) .* ...
                                   navdata_(:,:,p+1,zn,t).*repmat(corrpos(:,zn,t),1,Nc) , 2 ));
    end
  end
end

%% Now, check to see if the correction improved the phase differences:

clf
for t=2:Nt
%   for zn=1:Nz
  for zn=4
    plot( angle([ctemp(:,zn,t) ctemp_corr(:,zn,t)]) );
    ylim(0.5*[-1 1])
    legend('uncorrected','corrected')
    pause
  end
end
```

Plot an example:

```
t = 10; zn=4;
clf
plot( angle([ctemp(:,zn,t) ctemp_corr(:,zn,t)]) );
xlim([0 Nx+1])
ylim(0.4*[-1 1])
xlabel('Position')
ylabel('Phase difference odd-even navigators')
legend('uncorrected','corrected')
% zoom in:
axes('Position',[0.5 0.15 0.38 0.3])
plot( angle([ctemp(:,zn,t) ctemp_corr(:,zn,t)]) );
xlim([0 Nx+1])
ylim(0.03*[-1 1])
```
https://github.com/gadgetron/gadgetron/files/542778/odd-even_phase_diff_example.pdf

do a polynomial fit of the residual ctemp\_corr:
```
ctemp = complex(zeros(Nx,Nz,Nt));
slope = zeros(Nz,Nt);
intercept = zeros(Nz,Nt);
corrpos = complex(zeros(Nx,Nz,Nt));
corrneg = complex(zeros(Nx,Nz,Nt));
ctemp_corr = complex(zeros(Nx,Nz,Nt));
phase_poly_coef = zeros(5,Nz,Nt);

X = zeros(Nx, 5);
X(:,1) = ones(Nx,1);
X(:,2) = x;
X(:,3) = x.^2;
X(:,4) = x .* X(:,3);
X(:,5) = X(:,3).^2;

for t=1:Nt
  for zn=1:Nz
%   for zn=4

    ctemp_odd = zeros(Nx,1);
    % Phase difference nav1/nav3 and nav2:
    for p=1:(Nnavs-2)
      % combine across coils (and accumulate across triplets):
      ctemp(:,zn,t) = ctemp(:,zn,t) + squeeze(sum( conj( navdata_(:,:,p  ,zn,t).*repmat(1./corrB0(:,zn,t),1,Nc) + ...
                                         navdata_(:,:,p+2,zn,t).*repmat(corrB0(:,zn,t),1,Nc) ) .* ...
                                   navdata_(:,:,p+1,zn,t) , 2 ));
      ctemp_odd = ctemp_odd + 0.5*sqrt( sum( abs( navdata_(:,:,p  ,zn,t) ).^2, 2 ) ) + ...
                              0.5*sqrt( sum( abs( navdata_(:,:,p+2,zn,t) ).^2, 2 ) );
    end
    slope(zn,t) = (Nx-1) * squeeze(angle( sum(conj(ctemp(1:end-1,zn,t)).*ctemp(2:end,zn,t)) ));
    % remove the slope
    ctemp(:,zn,t) = ctemp(:,zn,t) .* exp(-1i*slope(zn,t)*x);
    intercept(zn,t) = squeeze(angle(sum(ctemp(:,zn,t))));
    tvec = slope(zn,t)*x + intercept(zn,t);

    % since we have already removed the slope, remove now the intercept:
    ctemp(:,zn,t) = ctemp(:,zn,t) .* exp(-1i*intercept(zn,t));
    
    % polynomial fit:
    WX = diag( ctemp_odd ) * X;
    Wctemp = ctemp_odd .* angle(ctemp(:,zn,t));
    phase_poly_coef(:,zn,t) = WX\Wctemp;
    
    % update the correction:
    tvec = tvec + X*phase_poly_coef(:,zn,t);

    
    corrpos(:,zn,t) = exp(-1i*0.5*tvec);
    corrneg(:,zn,t) = exp( 1i*0.5*tvec);
    for p=1:(Nnavs-2)
      % combine across coils (and accumulate across triplets):
      ctemp_corr(:,zn,t) = ctemp_corr(:,zn,t) + squeeze(sum( conj( navdata_(:,:,p  ,zn,t).*repmat(corrneg(:,zn,t)./corrB0(:,zn,t),1,Nc) + ...
                                         navdata_(:,:,p+2,zn,t).*repmat(corrneg(:,zn,t).*corrB0(:,zn,t),1,Nc) ) .* ...
                                   navdata_(:,:,p+1,zn,t).*repmat(corrpos(:,zn,t),1,Nc) , 2 ));
    end
  end
end


%%

clf
for t=2:Nt
  for zn=1:Nz
%   for zn=4
%     subplot(2,1,1)
%     plot( angle(ctemp(:,zn,t)) );
%     subplot(2,1,2)
%     plot( angle(ctemp_corr(:,zn,t)) );
%     ylabel('corrected')
    plot( angle([ctemp(:,zn,t) ctemp_corr(:,zn,t)]) );
    ylim(0.05*[-1 1])
    legend('uncorrected','corrected')
    pause
  end
end

%%

t = 10; zn=4;
clf
plot( angle([ctemp(:,zn,t) ctemp_corr(:,zn,t)]) );
xlim([0 Nx+1])
ylim(0.03*[-1 1])
xlabel('Position')
ylabel('Phase difference odd-even navigators')
legend('after linear fit','after polynomial fit')
hold on
plot( [0 Nx+1], [0 0], 'k' )
hold off
```
https://github.com/gadgetron/gadgetron/files/542790/odd-even_phase_diff_poly_fit_example.pdf

**Comment by hansenms** [comment]
This looks good. I would prefer it if the selection for correction was an enumeration rather than an integer, which could be set to an invalid value. There are lots of examples, see for instance:

https://github.com/gadgetron/gadgetron/blob/542ceeed28de125df44ed925a6de09487f188d92/gadgets/mri_core/ImageSortGadget.h

Would that make sense?

**Comment by pvelasco** [comment]
That's a very good point.  I'll modify it and add a new commit to this PR.

PS: Sorry about the sound during the call, earlier.  I tested the camera and the sound output, but not the mic...

**Comment by pvelasco** [comment]
I just committed the changes to make them enumeration.

**Pull request merged**
