### PR TITLE
Update to CUDA 11.6

### PR DESCRIPTION
**Pull request by hansenms**
This PR updates to CUDA 11.6 and switches to the nvidia channels for CUDA. There is a small workaround for the thrust namespace in one .cu file. This should build on GPU and non-GPU machines.

### CODE REVIEW

**Review by johnstairs — APPROVED** [review]

**Comment by johnstairs** [comment]
`build-images.sh` runs file on my machine without GPUs.

**Comment by hansenms** [comment]
Thanks @johnstairs!

@kristofferknudsen do you want to give it a go as well?

**Comment by kristofferknudsen** [comment]
I've given it a whirl, it looks good :+1: 

The docker images build without issues for me, and the pass what tests I can run. I can't attach my GPU to the container, but I have no reason to doubt that it works in other contexts. 

It also builds natively on Fedora 35, with gcc 11.2.1-1, and CUDA 11.6. Tests pass.

**Comment by hansenms** [comment]
Thanks @kristofferknudsen, let's ship it!

**Pull request merged**
