### PR TITLE
Added gadget to split a 3D volume into slices.

### PR DESCRIPTION
**Pull request by inati**
Waiting on making a good integration test, but this seems to work as advertised.

### CODE REVIEW

**Comment by inati** [comment]
Note the slice positions are wrong still.  Need to fix this.

**Comment by hansenms** [comment]
Should we wait to merge until you have a test?

**Comment by hansenms** [comment]
@inati, what is the status of this?

**Comment by hansenms** [comment]
@inati, "ping". What would you like to do about this?

**Comment by inati** [comment]
We do need this gadget for some things, and I will finish it, but I would prefer that the generic chains send 3D data all the way through and have the client be responsible for what to do.  @xueh2 and I worked on having the client on the siemens scanner side handle 3D - we still need to test more, but we got the desired behavior.  I will take another pass at this gadget tomorrow and finish it up.

**Comment by hansenms** [comment]
I am closing this since it is no longer able to merge and nothing has happened to it for a while.

**Pull request closed without merging**
