### PR TITLE
'Fixed' compilation warnings

### PR DESCRIPTION
**Pull request by kristofferknudsen**
We fixed a number of warnings during Gadgetron compilation. See individual commits for details. 

Minor changes to CMake files, including an update to the way we find Python, and -Werror where possible.

### CODE REVIEW

**Review by hansenms — CHANGES_REQUESTED** [review]
This is a really great PR. So nice to see a build running without warning. Massive kudos for taking this on, huge amount of effort.

My biggest concern here is maybe not so much a problem with the PR but more of a problem with missing tests overall. Many of the Gadgets that have changes get exercised in integration tests, so I feel pretty confident with the tests passing on those, but then there are a number that are either never tested or never even used in a pipeline and some of them have pretty extensive testing in this PR. The physio interp gadget would be a prime example. Here is a (probably not exhaustive list) of the most problematic cases:

* CMRTGadget
* NFFT2DGadget
* RegistrationAveragingGadget
* CplxDumpGadget
* PhysioInterpolationGadget (pretty extensive changes here)
* gpuGenericSensePrepGadget
* gpuRadialPrepGadget (not even referenced in a pipeline)
* gpuRetroGatedSensePrepGadget (not even referenced in a pipeline)
* RadialPhaseCorrectionGadget (not even referenced in a pipeline)

I would actually suggest that we take the changes in those on this PR and park them in a branch and remove all of them and their associated pipelines if there are any. I am pretty sure they are never used. If some of them are, we should add test coverage to validate that we are doing the right thing....add tests before this PR that is.

**Comment by dchansen** [comment]
@rajramasawmy Could you comment on the usage of the GPU gadgets? 

@xueh2 Do you have any of the listed Gadgets in use?

@hansenms I'm generally in favor of removing everything that has no tests. Pipelines, toolboxes, etc. There should perhaps be some exceptions (i.e. the ISMRMRDdump versions of a lot of pipelines), but I like it as a policy.

gpuRadialPrepGadget is a base class for gpuRadialSensePrepGadget, which has several tests, so that should be kept. Or rewritten.

**Comment by kristofferknudsen** [comment]
I note that these are just the Gadgets touched by this pull request. We probably have more untested Gadgets lying around, who are not in the list because their compilation did not produce a warning. I think we're dealing with multiple tiers of disuse here. 

1. There's a set of Gadgets who are not mentioned in any of the config files we install. 
Banish them all. 
2. There's a set of Gadgets who are mentioned in a config file, but not touched by an integration test. 
Add a test or banish the Gadget.
3. There's a set of Gadgets who are used in integration tests. 
I guess they can stay.

I don't much care if the Gadgets are actually being used. If there are no tests, we can't maintain them. If they are being used, we can either add a test, or hand them over to those using them though. Still get's them out of case 2. 

I think we need a full list though, before we can go ahead. I'll see if I can't compile a full set for each case above. I suspect there's more than just the nine.

**Comment by hansenms** [comment]
I think we are in 100% agreement here. Any attempt to maintain code over time without at least some smoke tests is a fool's errand. I think we should as you both say remove anything that is not being exercises in some kind of test.

I also completely agree that there many more gadgets than the ones touched in this PR that should be removed. And actually some of the standalone apps, etc, that are not used or maintained. Some spring cleaning would be in order to make things more maintainable.

In the context of this PR, it becomes maybe more of a mechanical question, do we:

1. Get this PR merged as best as we can knowing that there may be gadgets (etc.) that used to work, but will be broken after this PR, but we will not know since we don't have tests. We can then do a spring cleaning exercise afterwards? or 
2. Do we try to remove Gadgets that are touch by this PR but not tested now. And then do more spring cleaning.

What do you think is better/more practical. I can see advantages to both.

**Comment by kristofferknudsen** [comment]
So- eh- there's more than nine.

I wrote a small script, to have a look at the test coverage. Obviously, I banged it together with some haste, and I may have overlooked something crucial. 

I was going to attach the script, but github doesn't accept .py files. It's pretty short, so I'll just paste it in below. It's at the bottom, all the way down.  

Results are as follows: 
- We test 46 out of 114  config files. (~40% coverage)
- We test 47 out of 137 Gadgets. (~34% coverage) 

This says nothing about code coverage in the individual Gadgets, of course. Just whether they ever get loaded into memory. 

Even if I'm wrong about two-thirds of these Gadgets, I still think the banishment is too large an event to sneak onto the end of this PR. I suggest we merge this as is, accept any reports of breakage with open arms - (please provide a test for the future sir) - and start **OPERATION BANISHMENT** in a pull request of it's own. And we should probably also bump some sort of major version, while we're at it.

The script produces a very accusatory list as output (it has nice colors when run in a terminal) - I urge all to have a look, and see if there's something unreasonable in there. 

Output is broadly structured as:

- Set of config file that are tested (yay!)
- Set of config files that are not tested (booo!)
- Set of Gadgets that are tested (yay!)
- Set of Gadgets that are not tested (booo!) 

```bash
root@fedora:/opt/code/banishment# python3 test_coverage.py --test-folder=/Gradient/gadgetron/test/integration/cases/ --config-folder=/usr/local/share/gadgetron/config/ --gadget-folder=/usr/local/lib/
Tested configuration files: (46)

{'CMR_2DT_RTCine_KspaceBinning.xml',
 'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',
 'CMR_2DT_T1Mapping_SASHA.xml',
 'FS-CSI.xml',
 'Generic_Cartesian_Grappa.xml',
 'Generic_Cartesian_Grappa_Cine_Denoise.xml',
 'Generic_Cartesian_Grappa_EPI_AVE.xml',
 'Generic_Cartesian_Grappa_RealTimeCine_Python.xml',
 'Generic_Cartesian_Grappa_SNR.xml',
 'Generic_Cartesian_Grappa_T2W.xml',
 'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',
 'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine.xml',
 'Generic_Cartesian_Spirit_SASHA.xml',
 'deblurring_recon_acctrig.xml',
 'default.xml',
 'default_measurement_dependencies.xml',
 'default_optimized.xml',
 'distributed_default.xml',
 'distributed_generic_default.xml',
 'distributed_image_default.xml',
 'epi.xml',
 'external_equivalent_example.xml',
 'external_julia_acquisition_example.xml',
 'external_matlab_acquisition_example.xml',
 'external_matlab_bucket_example.xml',
 'external_matlab_buffer_example.xml',
 'external_matlab_tiny_example.xml',
 'external_python_acquisition_example.xml',
 'external_python_bucket_example.xml',
 'external_python_buffer_example.xml',
 'fixed_radial_mode1_gpu_ktsense.xml',
 'fixed_radial_mode1_gpusense_cg.xml',
 'fixed_radial_mode1_realtime.xml',
 'golden_radial_mode2_gpu_ktsense.xml',
 'golden_radial_mode2_gpusense_cg.xml',
 'golden_radial_mode2_gpusense_sb.xml',
 'golden_radial_mode2_realtime.xml',
 'grappa_float.xml',
 'grappa_float_cpu.xml',
 'parallel_bypass_example.xml',
 'python_buckets.xml',
 'python_image_array_recon.xml',
 'python_passthrough.xml',
 'python_short.xml',
 'spiral_flow_gpusense_cg.xml',
 'spiral_flow_gpusense_sb.xml'}

Untested configuration files: (68)

{'CMRT.xml',
 'CMRT3D.xml',
 'CMR_2DT_RTCine_KspaceBinning_MultiSeries.xml',
 'CMR_2DT_RTCine_KspaceBinning_MultiSeries_Cloud.xml',
 'CMR_Image_Chain_RTCine_LAX_AI.xml',
 'CMR_RTCine_LAX_AI.xml',
 'Generic_CPU_Gridding_Recon.xml',
 'Generic_Cartesian_FFT.xml',
 'Generic_Cartesian_Grappa_AI.xml',
 'Generic_Cartesian_Grappa_EPI.xml',
 'Generic_Cartesian_Grappa_FatWater.xml',
 'Generic_Cartesian_Grappa_RealTimeCine.xml',
 'Generic_Cartesian_Grappa_RealTimeCine_Cloud.xml',
 'Generic_Cartesian_Grappa_SNR_CoilQA.xml',
 'Generic_Cartesian_Image_Chain_FFT.xml',
 'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',
 'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',
 'Generic_Cartesian_Spirit.xml',
 'Generic_Cartesian_Spirit_RealTimeCine.xml',
 'Generic_Spiral.xml',
 'Generic_Spiral_Flag.xml',
 'Generic_Spiral_SNR.xml',
 'MOLLI_T1_Moco.xml',
 'MOLLI_T1_Moco_istore.xml',
 'NFFT2D.xml',
 'NoiseSummary.xml',
 'default_measurement_dependencies_ismrmrd_storage.xml',
 'default_short.xml',
 'epi_gtplus_grappa.xml',
 'external_connect_example.xml',
 'external_example.xml',
 'fixed_radial_mode0_gpu_ktsense.xml',
 'fixed_radial_mode0_gpusense_cg.xml',
 'fixed_radial_mode0_gpusense_cg_unoptimized.xml',
 'fixed_radial_mode0_gpusense_sb.xml',
 'fixed_radial_mode0_gpusense_sb_unoptimized.xml',
 'fixed_radial_mode0_realtime.xml',
 'fixed_radial_mode1_gpusense_cg_unoptimized.xml',
 'fixed_radial_mode1_gpusense_sb.xml',
 'fixed_radial_mode1_gpusense_sb_unoptimized.xml',
 'generic_gpu_ktsense_singleshot.xml',
 'generic_gpusense_cg.xml',
 'generic_gpusense_cg_singleshot.xml',
 'generic_gpusense_nlcg_singleshot.xml',
 'generic_gpusense_sb_singleshot.xml',
 'golden_radial_mode2_gpusense_cg_unoptimized.xml',
 'golden_radial_mode2_gpusense_nlcg.xml',
 'golden_radial_mode2_gpusense_nlcg_unoptimized.xml',
 'golden_radial_mode2_gpusense_sb_unoptimized.xml',
 'golden_radial_mode3_gpusense_cg.xml',
 'golden_radial_mode3_gpusense_sb.xml',
 'golden_radial_mode3_os_realtime.xml',
 'grappa.xml',
 'grappa_cpu.xml',
 'grappa_device.xml',
 'grappa_device_cpu.xml',
 'grappa_unoptimized.xml',
 'grappa_unoptimized_float.xml',
 'gtquery.xml',
 'isalive.xml',
 'ismrmrd_dump.xml',
 'pseudoreplica.xml',
 'spiral_flow_generic_gpusense_cg.xml',
 'spiral_flow_generic_gpusense_sb.xml',
 'spiral_flow_gpusense_cg_unoptimized.xml',
 'spiral_flow_gpusense_sb_unoptimized.xml',
 'spiral_interactive.xml',
 'spirit.xml'}

Tested Gadgets: (47)

{'AcquisitionAccumulateTriggerGadget',
 'AcquisitionDistributor',
 'AcquisitionFanout',
 'AcquisitionReader',
 'AsymmetricEchoAdjustROGadget',
 'BucketToBufferGadget',
 'BufferDistributor',
 'BufferReader',
 'BufferWriter',
 'CmrCartesianKSpaceBinningCineGadget',
 'CoilReductionGadget',
 'ComplexToFloatGadget',
 'DenoiseGadget',
 'ExtractGadget',
 'FloatToUShortGadget',
 'GadgetIsmrmrdAcquisitionMessageReader',
 'GadgetIsmrmrdAcquisitionMessageWriter',
 'GadgetIsmrmrdWaveformMessageReader',
 'GenericReconCartesianGrappaGadget',
 'GenericReconCartesianReferencePrepGadget',
 'GenericReconEigenChannelGadget',
 'GenericReconFieldOfViewAdjustmentGadget',
 'GenericReconImageArrayScalingGadget',
 'GenericReconKSpaceFilteringGadget',
 'GenericReconPartialFourierHandlingPOCSGadget',
 'ImageAccumulator',
 'ImageArraySplitGadget',
 'ImageFanout',
 'ImageFinishGadget',
 'ImageIndexGadget',
 'ImageInverter',
 'ImageLayerer',
 'ImageSortGadget',
 'ImageWriter',
 'IsmrmrdImageArrayReader',
 'IsmrmrdImageArrayWriter',
 'MRIImageReader',
 'MRIImageWriter',
 'NoiseAdjustGadget',
 'PCACoilGadget',
 'RemoveROOversamplingGadget',
 'SimpleReconGadget',
 'SliceAccumulator',
 'Unmixing',
 'WaveformReader',
 'cpuWeightsCalculator',
 'gpuWeightsCalculator'}

Untested Gadgets: (90)

{'AccumulatorGadget',
 'AcquisitionPassthroughGadget',
 'AutoScaleGadget',
 'CMRT3DGadget',
 'CMRTGadget',
 'CPUGriddingReconGadget',
 'CSIGadget',
 'CartesianToGenericGadget',
 'ChannelReorderer',
 'CmrParametricT1SRMappingGadget',
 'CmrParametricT2MappingGadget',
 'CmrRealTimeLAXCineAIAnalysisGadget',
 'CoilComputationGadget',
 'CombineGadget',
 'CplxDumpGadget',
 'CropAndCombineGadget',
 'CutXGadget',
 'DependencyQueryGadget',
 'DeviceChannelSplitterGadgetCPLX',
 'DeviceChannelSplitterGadgetFLOAT',
 'DeviceChannelSplitterGadgetUSHORT',
 'EPICorrGadget',
 'EPIPackNavigatorGadget',
 'EPIReconXGadget',
 'FFTGadget',
 'FFTXGadget',
 'FatWaterGadget',
 'FlagTriggerGadget',
 'FloatToIntGadget',
 'FloatToShortGadget',
 'FloatToUIntGadget',
 'FlowPhaseSubtractionGadget',
 'GenericImageReconArrayToImageGadget',
 'GenericImageReconGadget',
 'GenericReconAccumulateImage2DTriggerGadget',
 'GenericReconAccumulateImage3DTriggerGadget',
 'GenericReconCartesianFFTGadget',
 'GenericReconCartesianGrappaAIGadget',
 'GenericReconCartesianNonLinearSpirit2DTGadget',
 'GenericReconCartesianSpiritGadget',
 'GenericReconDataBase',
 'GenericReconGadget',
 'GenericReconImageBase',
 'GenericReconImageHeaderBase',
 'GenericReconImageToImageArrayGadget',
 'GenericReconKSpaceReadoutBase',
 'GenericReconNoiseStdMapComputingGadget',
 'GenericReconPartialFourierHandlingFilterGadget',
 'GenericReconReferenceKSpaceDelayedBufferGadget',
 'GriddingReconGadget',
 'ImageAccumulatorGadget',
 'ImageFFTGadget',
 'ImageResizingGadget',
 'ImageWriterGadgetCPLX',
 'ImageWriterGadgetFLOAT',
 'ImageWriterGadgetUSHORT',
 'IsmrmrdDumpGadget',
 'MaxwellCorrectionGadget',
 'NFFT2DGadget',
 'NoiseAdjustGadget_unoptimized',
 'NoiseCovariancePlottingGadget',
 'NoiseSummaryGadget',
 'OneEncodingGadget',
 'PhysioInterpolationGadget',
 'PseudoReplicatorGadget',
 'RadialPhaseCorrectionGadget',
 'RateLimitGadget',
 'ScaleGadget',
 'SpiralToGenericGadget',
 'T1MocoGadget',
 'WhiteNoiseInjectorGadget',
 'cpuRegistrationAveragingGadget2D',
 'cuFFTGadget',
 'gpuBufferSensePrepGadget',
 'gpuCSICoilEstimationGadget',
 'gpuCgKtSenseGadget',
 'gpuCgSenseGadget',
 'gpuCgSpiritGadget',
 'gpuGenericSensePrepGadget',
 'gpuLALMSenseGadget',
 'gpuNlcgSenseGadget',
 'gpuOsSenseGadget',
 'gpuRadialSensePrepGadget',
 'gpuRadialSpiritPrepGadget',
 'gpuRegistrationAveragingGadget2D',
 'gpuRegistrationScatteringGadget2D',
 'gpuRetroGatedSensePrepGadget',
 'gpuSbSenseGadget',
 'gpuSpiralDeblurGadget',
 'gpuSpiralSensePrepGadget'}

root@fedora:/opt/code/banishment# 
```

The test coverage script:
```python

import os
import sys
import glob

import re
import xml.etree.ElementTree as ElementTree

import pprint
import logging

import subprocess

import argparse
import configparser

_codes = {
    'red': '\033[91m',
    'green': '\033[92m',
    'cyan': '\033[96m',
    'bold': '\033[1m',
    'end': '\033[0m',
}


def find_installed_config_files(folder):
    return set(os.path.basename(filename)
               for filename
               in glob.glob(os.path.expanduser(os.path.join(folder, '*.xml'))))


def find_tested_config_files(folder):
    filenames = glob.glob(os.path.expanduser(os.path.join(folder, '*.cfg')))

    tested_configuration_files = set()

    for filename in filenames:

        config = configparser.ConfigParser()
        config.read(filename)

        for section in config.sections():
            if 'configuration' in config[section]:
                tested_configuration_files.add(config[section]['configuration'])

    return tested_configuration_files


def find_installed_gadgets(folder):
    object_files = glob.glob(os.path.expanduser(os.path.join(folder, 'libgadgetron_*.so')))

    installed_gadgets = set()

    factory_pattern = re.compile(r"gadget_factory_export_(?P<gadget_name>.*)")

    for object_file in object_files:
        symbol_table = subprocess.run(['objdump', '-TC', object_file],
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE,
                                      check=True)

        for line in symbol_table.stdout.decode('utf-8').splitlines():
            match = re.search(factory_pattern, line)
            if match:
                installed_gadgets.add(match['gadget_name'])

    return installed_gadgets


def find_gadgets_in_configuration_files(folder, files):

    gadgets = set()

    for filename in (os.path.expanduser(os.path.join(folder, file)) for file in files):

        try:
            parsed = ElementTree.parse(filename)
            for gadget in (node.text for node in parsed.findall('.//classname')):
                gadgets.add(gadget)

        except FileNotFoundError:
            continue

    return gadgets


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('--test-folder')
    parser.add_argument('--config-folder')
    parser.add_argument('--gadget-folder')

    args = parser.parse_args()

    tested_configuration_files = find_tested_config_files(args.test_folder)
    untested_configuration_files = find_installed_config_files(args.config_folder) - tested_configuration_files

    print(f"{_codes['bold']}Tested configuration files:{_codes['end']} ({len(tested_configuration_files)})")
    print(f"{_codes['green']}")
    pprint.pprint(tested_configuration_files)
    print(f"{_codes['end']}")

    print(f"{_codes['bold']}Untested configuration files:{_codes['end']} ({len(untested_configuration_files)})")
    print(f"{_codes['red']}")
    pprint.pprint(untested_configuration_files)
    print(f"{_codes['end']}")

    tested_gadgets = find_gadgets_in_configuration_files(args.config_folder, tested_configuration_files)
    untested_gadgets = find_installed_gadgets(args.gadget_folder) - tested_gadgets

    print(f"{_codes['bold']}Tested Gadgets:{_codes['end']} ({len(tested_gadgets)})")
    print(f"{_codes['green']}")
    pprint.pprint(tested_gadgets)
    print(f"{_codes['end']}")

    print(f"{_codes['bold']}Untested Gadgets:{_codes['end']} ({len(untested_gadgets)})")
    print(f"{_codes['red']}")
    pprint.pprint(untested_gadgets)
    print(f"{_codes['end']}")


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main()
```

**Comment by hansenms** [comment]
Hah, this is brilliant @kristofferknudsen, thanks for doing that script! It is of course quite disturbing but the only path to sorting this out is knowing about it.

Looking through the pipelines that are not being tested, I definitely see some that should be and that are in use. Like the Coil QA one and some others. We should have tests for those. There are also pipelines that may not be exercised by tests, but they are small variations of others that are....like same pipeline producing either float or short output. We can relatively easily make sure they are tested. So I think with a modest effort we can get the pipeline coverage closer to two thirds. But there is some work to do it.

Definitely a lot of gadgets in the untested list that I will almost guarantee don't work anymore. And a few that are debugging tools that probably work and are in some use, but we should make sure we have pipelines that exercise them.

I wholeheartedly support operation banishment. I doubt it will be (or should be) a single PR, but we can start with this list an whittle away at it as a group effort. I might also suggest that we get a form of this script into the repo and generate an initial list of things that are slated for removal and commit that list to the repo and then on PRs check that nothing new is being added to the list so that at least we will not be making things worse while we work to reduce the list.

Given the scale of this effort, I agree, we should get this PR through without attempting to take this on in this context, then we can push a branch of which we can go back to later if we need to reanimate some of the stuff we banish. And then we start the process.

@kristofferknudsen thanks again for all the work on this. Would you mind resolving the current conflicts and merge in master (I suspect this is just the typos PR that is causing problems here). I will then make sure the build runs and get this merged.

**Comment by hansenms** [comment]
@kristofferknudsen wanna resolve the conflicts so we can get this one in?

**Review by hansenms — APPROVED** [review]

**Comment by hansenms** [comment]
@kristofferknudsen are you good for this to go in? @dchansen any reservations?

**Comment by dchansen** [comment]
Looks good to me 👍

**Pull request merged**
