### PR TITLE
updating MatlabGadgets to use new GADGET_PROPERTY

### PR DESCRIPTION
**Pull request by naegelejd**

### CODE REVIEW

**Comment by inati** [comment]
This looks good to me.  Were you able to test?

**Comment by naegelejd** [comment]
Yep, `matlab.xml` works with the dataset generated by `ismrmrd_generate_cartesian_shepp_logan`. I tested with R2014b.

The other two chains use the `MatlabBufferGadget` and run without any errors but one is for non-cartesian data and the other I'm unsure about, so neither actually reconstructed anything for me.

**Comment by inati** [comment]
@dchansen I have merged, but please make sure your non-cartesian matlab stuff works with these changes.

**Comment by hansenms** [comment]
Please don't merge new commits when the buildbot is failing. Not good practice.

**Comment by inati** [comment]
I have not received any notification emails saying that buildbot was failing.  Perhaps we can change the buildbot email config so that all those that have permission to merge a pull receive the emails regardless of the blame list.  Alternatively, we need to have a rule that we must be that we check the buildbot website before committing to master.

**Comment by hansenms** [comment]
Windows builder is failing and we are trying to resolve it. Adding new commits to that is not helpful

**Comment by inati** [comment]
Understood. And I see that now that I look at the webpage, but there was no way for me to know that without looking.   Sorry.

**Comment by hansenms** [comment]
Please check before merging.

------

**Pull request merged**
