### PR TITLE
improve the scalability of non local denoising

### PR DESCRIPTION
**Pull request by xueh2**
refactor the denoising code

a) separate critical part of code out
b) make the parallel part of code run without barrier

it can now run ~700ms on my desktop, original it was running at ~2s

### CODE REVIEW

**Comment by xueh2** [comment]
Hi David,

I made a bit further change. By separating the critical part of code out, it can now scale better in 16 core computers. 

regards

Hui

**Comment by dchansen** [comment]
Hi Hui,

Unfortunately this pull request slows down the code significantly on fewer core machines (more than 2x slower on my  quad-core).  This is not really acceptable. We can't optimize only for 64 or even 16 core machines, as most users (excluding NIH) will be on much smaller machines (4-8 cores).

It also uses quite a bit of extra memory (about 0.5Gb per image for 256X256 images), but I guess we can live with that.

The "proper" way to parallelize would be to follow what is done in ["Noise Clinic"](http://www.ipol.im/pub/art/2015/125/) which avoids the pitfalls of both your and my implementation.

**Comment by xueh2** [comment]
Yes, you are correct. It is certainly slower for less number of cores and using ram, since apply patches is single-threaded.

I suppose the "noise clinic" solution will take some time to implement?

since most hospital deployment has >=16 cores, they will get faster speed. if the absolution processing time of <8 cores is not too bad, maybe we could put this in with "TODO" to let hospitals get the benefits now. Peter is quite keen to get this out there in some LGE chains and maybe t2*.

**Comment by xueh2** [comment]
Hi David,

I added back the original code pieces for less number of cores. TODO is to improve them once we have time to get on this.

Is this good for now?

regards

Hui

**Comment by dchansen** [comment]
Hi Hui,

Sure, this will do for now.

**Comment by dchansen** [comment]
Hui, 
Something is off. The new code is several orders of magnitude slower when running on a 32 core machine, literally going from 0.5s to 25s. 
I'm reverting this pull change. 
Could you make add a test data set for the denoiser? That way at least we're running on the same data.

**Comment by xueh2** [comment]
Ok, that is wired ... I will add a test case into integration.

**Pull request merged**
