### PR TITLE
turn off outer loop openmp for 3D recon

### PR DESCRIPTION
**Pull request by xueh2**
turn off outer loop openmp for 3D recon

### CODE REVIEW

**Comment by hansenms** [comment]
Do you have some speed tests on this?

**Comment by xueh2** [comment]
I did some speed test.
For a test case, embedded, R=3*3, 33*33 calibration region, without this change, the calibration steps ran in in single threaded and took  
GenericReconCartesianGrappaGadget::perform_calib:178441.891000 ms

With the change, the calibration step ran in multi-threading and took 
GenericReconCartesianGrappaGadget::perform_calib:40434.372000 ms

**Comment by hansenms** [comment]
OK, I should merge then?

**Comment by xueh2** [comment]
Yes, this fix will help overall

**Pull request merged**
