### PR TITLE
add send RGB images

### PR DESCRIPTION
**Pull request by xueh2**
add GenericImageReconGadget::sendOutRGBImages

### CODE REVIEW

**Comment by xueh2** [comment]
Please review the PR.

**Comment by hansenms** [comment]
@xueh2 I am having a bit of a hard time reviewing this without understanding the motivation or use of this. The definition of the RGB image type seems a bit opaque to me. It is also very repetitive and a bit old school, but I could be missing something. I suggest we set up some time to do a PR walk-through, that would probably help.

The code does not appear to be called or tested in anyway. Is that on purpose?

There are also a few thinks like:

```
try {

} catch (...) {
   throw;
} 
```

Not sure I am totally getting that.

**Comment by hansenms** [comment]
@xueh2 last call on this and then I think we should close and we can reopen when needed.

**Comment by xueh2** [comment]
Ok, agreed. I will rework this and reopen it later.

**Pull request closed without merging**
