### PR TITLE
Removed the need for both gadget_reference and next_gadget in base pytho...

### PR DESCRIPTION
**Pull request by hansenms**
@naegelejd , could you have a look at this and see what you think. I think the need for gadget_reference is removed. We should be able to make standalone Python chains now based on this.

### CODE REVIEW

**Comment by naegelejd** [comment]
When each of the existing gadgets calls `self.put_next()` they call `astype('complex64')` on the data array, but that's called again in the base class if the `next_gadget` is of type `GadgetronPythonMRI.GadgetReference`. Couldn't the gadgets just call `self.put_next(header, data)` without worrying about the type of `data`?

**Comment by hansenms** [comment]
Yes, those conversions can now be handled by the base class. I'll make that change.

------

**Comment by hansenms** [comment]
@naegelejd , I have changed it as discussed. 

One other thing to consider is what should be returned (if anything) from process and how that is handled on the Gadgetron side. But that can be modified later. 

Would you be happy to get this merged now?

**Comment by naegelejd** [comment]
Yep this is great.

**Pull request merged**
