### PR TITLE
adding ISMRMRD header converters to python toolbox

### PR DESCRIPTION
**Pull request by naegelejd**
This greatly simplifies the GadgetronPythonMRI boost python
module and allows Python gadgets to use the Python ISMRMRD
package (github.com/ismrmrd/ismrmrd-python).

### CODE REVIEW

**Comment by inati** [comment]
Looks great!  Are we ready to merge or will it break the buildbots?

**Comment by naegelejd** [comment]
Not yet, Michael had trouble getting `pyxbgen` to run in the Ubuntu 14.04 `chroot`. We still have to figure that out but I'm not sure I understand why the buildslave script can't find the executable if it's installed in `/usr/local/bin` and that's on the `$PATH`.

**Comment by hansenms** [comment]
I figured out what the problem was, I think. We had two 14.04 buildslaves, one on vatican and one on grenada. I clicked the grenada buildslave and said rebuild, but it actually triggered a rebuild on vatican where pyxbgen was not yet installed. After installing on both buildslaves it seems to work.

I will review this and merge. But it will probably break the windows and mac build slaves. 

@puletic, I need you to install PyXB on the Windows and Mac build slaves, @naegelejd will you give a hand with running pip install on those two hosts.

**Comment by hansenms** [comment]
We have the following problem. The version of h5py included with Ubuntu 14.04 does not seem to support vlen for other than strings:

    2015-03-02 20:15:48 DEBUG [PythonGadget.h:37] Python Module          : remove_2x_oversampling
    2015-03-02 20:15:48 DEBUG [PythonGadget.h:38] Python Class           : Remove2xOversampling
    2015-03-02 20:15:48 DEBUG [PythonGadget.h:78] Error loading python modules in Gadget RemoveOversamplingPython
    Traceback (most recent call last):
      File "/home/hansenms/local/gadgetron/bin/..//share/gadgetron/python/remove_2x_oversampling.py", line 4, in <module>
        from gadgetron import Gadget
      File "/home/hansenms/local/gadgetron/bin/..//share/gadgetron/python/gadgetron.py", line 3, in <module>
        import ismrmrd
      File "/usr/local/lib/python2.7/dist-packages/ismrmrd/__init__.py", line 4, in <module>
        from .hdf5 import Dataset
      File "/usr/local/lib/python2.7/dist-packages/ismrmrd/hdf5.py", line 50, in <module>
    ('traj', h5py.special_dtype(vlen=np.dtype('float32'))),
      File "h5t.pyx", line 1486, in h5py.h5t.special_dtype (h5py/h5t.c:14064)
    NotImplementedError: Only byte or unicode string vlens are currently supported
    2015-03-02 20:15:48 DEBUG [Gadget.h:161] Gadget (RemoveOversamplingPython) process config failed

Thoughts?

**Comment by inati** [comment]
The Python stuff is almost always out of date before you blink. Sigh.

You can do this to install the latest:
pip install -U h5py

I don't remember having to do this on my machine, but I might have and forgotten.



Sent with a mobile device

-----Original Message-----

**Comment by hansenms** [comment]
pip install -U h5py

Didn't work alone, I had to install cython first for some reason.

**Comment by inati** [comment]
Weird. That should no longer be required. I'll take a look



Sent with a mobile device

-----Original Message-----

**Comment by hansenms** [comment]
Installing cython was required for installing h5py, not sure why.

**Comment by inati** [comment]
Oh, that's right, h5py requires cython.

So it seems that the python packages are woefully out of date, even in a distro like Ubuntu which stays reasonably up to date.   We'll have to steer people to pip.

Looks like we require 2.3 or greater.  I will see about forcing that somehow.

**Comment by hansenms** [comment]
I have updated the two Linux build slaves, so I am merging now. But it will likely bomb on the Mac and Windows slaves. We shall see.

**Pull request merged**
