### PR TITLE
Fixed bug in matlab buffer conversion.

### PR DESCRIPTION
**Pull request by inati**
Reference data was not being sent properly.

### CODE REVIEW

**Comment by hansenms** [comment]
The matlab stuff from your last commit is failing. There seems to be some scaling problem now.

**Comment by inati** [comment]
Found the problem.  There was a bug in the old code
sqrt(sum(im.^2))
instead of 
sqrt(sum(abs(im).^2))
I will need to upload a new reference data set and update the test.

**Comment by hansenms** [comment]
@inati let me know when you have uploaded the new reference data.

**Comment by inati** [comment]
Okay, the last commit fixes the integration test by correct the ssos and fft scaling.  matlab.xml and default.xml give the same answer, so we don't need a new dataset.

**Pull request merged**
