### PR TITLE
main_sb.cpp rename shadow variable

### PR DESCRIPTION
**Pull request by maddin200**

### CODE REVIEW

**Comment by hansenms** [comment]
What is the context for this?

**Comment by maddin200** [comment]
shadows line 57 GPUTimer *timer;

**Comment by hansenms** [comment]
Yeah, not sure we should be taking code changes to this untested code. I am more inclined to remove it all together. Are you actually using this code?

**Comment by maddin200** [comment]
No  would be fine if it is not used.

**Pull request closed without merging**
