### PR TITLE
Add wavelet oper

### PR DESCRIPTION
**Pull request by xueh2**
add hoWavelet operator for 1D, 2DT and 3D
add moco operator
add coil combination utility function in mri_core
add a few missing instantiation functions in hoNDArray_elemwise.cpp

Old operators were replaced with new ones. Nonlinear recon image quality is improved, as a bug was fixed with new operators.

### CODE REVIEW

**Comment by hansenms** [comment]
Can we squash these commits. That is a crazy number of commits.

**Comment by hansenms** [comment]
Why are is there a 2D coil combine and a 3D, can't that be generalized. And why is the implementation so different. The 2D one seems to be handling some special case of mismatch between data size and number of coils. Looks less than general. What is the story?

**Comment by xueh2** [comment]
The coil_combine function is consolidated. Only one general function is added.

I will squash the commits after all changes are made and force update the PR later.

**Comment by hansenms** [comment]
I think this is OK now. Let's get these commits squashed.

**Comment by xueh2** [comment]
Squashed into two commits

**Comment by xueh2** [comment]
Should I do the merge now?

**Pull request merged**
