### PR TITLE
update chroot install script for docker based solution

### PR DESCRIPTION
**Pull request by xueh2**
Update chroot install script for docker images

### CODE REVIEW

**Comment by hansenms** [comment]
So this will now break the old chroot images, right. I don't think we should jump to making these changes until we are ready. You raised some performance issues today for instance, let's make sure we understand them.

**Comment by xueh2** [comment]
Yes, old chroot scheme will retire. The performance issue is not real. I did a reboot for barbados and the docker chroot based gadgetron ran just as fast as before.

**Comment by hansenms** [comment]
Not sure if we should merge this now, since it leaves us in a bit of an undefined situation. Options are:

1. Merged now and work fast to get the rest done. 
2. Change this script to detect if it is a new or an old style chroot
3. Change the script that creates the chroot from the docker image so that appends the path like the old one did.

Thoughts?

**Comment by xueh2** [comment]
I added a check to detect new docker based installation. So the installation script can be used for both new and old packages.

**Pull request merged**
