### PR TITLE
remove gt_index_type

### PR DESCRIPTION
**Pull request by gtdeveloper5**
fix issue #24 "Remove gt_index_type definition".

### CODE REVIEW

**Comment by hansenms** [comment]
Why is the the index defined as long long, shouldn't it be size_t

**Comment by gtdeveloper5** [comment]
It is because the most use case is for interpolator and boundary condition in image registration. Depending on the transformation, the input index position can be negative. So the index used in this process needs to be signed.

**Comment by hansenms** [comment]
I don't think it makes sense to have negative indexes into an array. Our NDArray structure is an array container and its design and interface should not be dictated by interpolators, etc. @inati, thoughts?

**Comment by inati** [comment]
Agreed.  Indices should never be negative as this allows for the possibility of weird errors.

**Comment by hansenms** [comment]
So Hui, this has to change. How are your thought on how to handle that?

**Comment by hansenms** [comment]
Actually, I am starting to see what is going on. All this boundary handler and point in range stuff is indicative of some pretty hacked up code outside the array. So the NDArray is and array container, it should not be interpreted in any spatial or other way, this needs to be changed.

**Comment by gtdeveloper5** [comment]
Yes, i made further changes and all array access uses size_t. Boundary condition and interpolator need long long, since they need to handle negative indices. I made a new pull request. So i am closing this one.

**Comment by hansenms** [comment]
I think all this special boundary condition handling should be done in a separate class. There is something not right about this mixing of memory containers and specific imaging interpretation of memory layouts.

**Pull request closed without merging**
