### PR TITLE
Switch CUDA_LIBRARIES to CUDA_CUDART_LIBRARY

### PR DESCRIPTION
**Pull request by PlutoniumHeart**
Signed-off-by: Zhitao Li <zhitaoli@email.arizona.edu>

Cmake 3.4 changed the return value for CUDA_LIBRARIES to some cuda
static libraries, including weird stuff like "-lpthread" and other
non-cuda libraries. The original lib returned by CUDA_LIBRARIES in
cmake 3.2 is now what is returned in CUDA_CUDART_LIBRARY.

This commit closes issue #227.

### CODE REVIEW

**Comment by hansenms** [comment]
The problem here is that this then breaks on every supported platform that we test. Specifically Ubuntu 14.04 ships with cmake 2.8 and latest cmake in brew (on the Mac) is 3.2, etc.

So what was your plan here?

**Comment by PlutoniumHeart** [comment]
I don't think this change would break backward compatibility, I have tested with cmake 2.8.12, 3.2.3, 3.4.1, all versions return the correct lib file name, which on my system is "/usr/local/cuda/lib64/libcudart.so", and compiles just fine.  

The only interesting thing is that these 2 variables only started to differ from cmake 3.3, and if you look at the FindCUDA.cmake file, it doesn't seem like a bug on the cmake side, that's probably one more reason for us to change as well...

But I have only tested on the machines I have, you guys should test on your's as well. 

BTW: I am on Debian Testing with cmake 3.4.1, cuda 7.5(with small modification to work with gcc-5.3).

**Comment by hansenms** [comment]
@dchansen do you have any thoughts/experience regarding this.

**Comment by hansenms** [comment]
When reading the FindCUDA documentation:

https://cmake.org/cmake/help/v3.4/module/FindCUDA.html

There is no mention of CUDA_CUDART_LIBRARY. I am a little worried about relying on an undocumented CMAKE variable. Where did you find the documentation for this variable?

**Comment by hansenms** [comment]
I'm also not really sure I get your comment "Cmake 3.4 changed the return value for CUDA_LIBRARIES to some cuda static libraries, including weird stuff like "-lpthread" and other non-cuda libraries." It is common that these library variable include other dependencies that are needed when linking. The issue with finding static and non-static libraries may come down to what you have installed on your system. 

I am not inclined to make this change, unless I am convinced that this will ultimately be the variable that needs to be used for CUDA linking. It looks like CUDA_LIBRARIES is still the right one, but you may have some issue on your system that is preventing that from working properly.

**Comment by PlutoniumHeart** [comment]
So this is the output of the variable CUDA_LIBRARIES from cmake 3.4: 

"/usr/local/cuda/lib64/libcudart_static.a-lpthread/usr/lib/x86_64-linux-gnu/librt.so/usr/lib/x86_64-linux-gnu/libdl.so"

As you can see, it not only includes additional libs, but also uses the static lib by default. While we are supposed to use libcudart.so.

I have 3 machines demonstrating the same problem with cmake version >=3.3, and I think there's someone on the #227 also reporting the same. 

I did notice that the variable I am using is not documented, it is indeed a little worrying...

**Comment by hansenms** [comment]
Sounds like it might be a bug in FindCUDA. The problem with changing to the undocumented variable, is that it is not guaranteed to include all the dependent libraries and I foresee a whole lot of problems that go along with this. What I would rather do is to change our:

https://github.com/gadgetron/gadgetron/blob/master/cmake/FindCUDA_advanced.cmake

Which is actually what we call so that it does the right thing when the version number is higher than whatever the appropriate number is. Then if we need to change it again, it is in one place and not spread out over tens of CMakeLists.txt files that may need to be updated as versions change. 

There is no siemens_client anymore. There is an open source siemens_to_ismrmrd converter:

https://github.com/ismrmrd/siemens_to_ismrmrd

And we have an ISMRMRD client.

**Comment by PlutoniumHeart** [comment]
Yes, I agree, it is kinda uncomfortable to use an undocumented variable. I will take a look into the FindCUDA_advanced.cmake further. 

Thanks for the link to siemens_to_ismrmrd.

**Comment by hansenms** [comment]
OK, let me know how it goes. I am closing this for now.

**Comment by PlutoniumHeart** [comment]
So I checked the cmake's FindCUDA.cmake file. Apparently they added a new option to allow people to use static CUDA lib, and by default this option is been turned on, and that's why it is returning different result. 

I reverted previous change, and added a single line to set this value to false, before calling find_package(CUDA 5.5), and that fixed the problem.  

The option is still available on the UI under CUDA, it's called CUDA_USE_STATIC_CUDA_RUNTIME, but using static lib is going to cause problems.

**Comment by PlutoniumHeart** [comment]
So I checked the cmake's FindCUDA.cmake file. Apparently they added a new option to allow people to use static CUDA lib, and by default this option is been turned on, and that's why it is returning different result. 

I reverted previous change, and added a single line to set this value to false, before calling find_package(CUDA 5.5), and that fixed the problem.  

The option is still available on the UI under CUDA, it's called CUDA_USE_STATIC_CUDA_RUNTIME, but using static lib is going to cause problems.

**Pull request closed without merging**
