### PR TITLE
Bug fix klt

### PR DESCRIPTION
**Pull request by xueh2**
fix for uncombined channels
remove some duplicates

### CODE REVIEW

**Comment by hansenms** [comment]
What bug exactly does this fix?

**Comment by xueh2** [comment]
The problem is line

453
-            output_length_ = output_length;

It should be:
+            output_length_ += unN;

There are also some code duplicates in 

prepare(const hoNDArray<T>& data, size_t dim, std::vector<size_t>& untransformed, value_type thres, bool remove_mean)

So the duplicates are removed.

**Comment by hansenms** [comment]
Is this related to the device channel problems of yesterday or is this something else?

**Comment by xueh2** [comment]
Yes, it is to fix the device channel error message. After debugging that dataset, this bug was found.

**Pull request merged**
