### PR TITLE
Create new writer FakeWriter to use a pipeline without writing any ou…

### PR DESCRIPTION
**Pull request by achataigner**
…tput.

### CODE REVIEW

**Comment by dchansen** [comment]
Sorry for not replying to this earlier. 
The FakeWriter approach should not be required anywhere (and certainly should never be a default writer). Adding a Gadget to the chain that takes all types as input and outputs nothing (a GenericChannelGadget) will achieve the same effect, and would be a lot cleaner.

**Comment by achataigner** [comment]
Sorry for this late answer David. Thank you for your help, I hope I will get some time this week to test your solution

**Comment by kristofferknudsen** [comment]
I'd like to add (in the interest of really very clean solutions), that the default behaviour since 4.0 has been to discard any messages not accepted by a writer. So having an empty set of writers would also ensure nothing is written to the client. Simply leave an empty `<writers/>` in your config and you should be good to go. 

This is the entirety of what's going on in the stream output thread:
```c++
    template<class F>
    void process_output(std::iostream &stream, Core::GenericInputChannel messages, F writer_factory) {

        auto writers = writer_factory();

        for (auto message : messages) {

            auto writer = std::find_if(
                    writers.begin(),
                    writers.end(),
                    [&](auto &writer) { return writer->accepts(message); }
            );

            if (writer != writers.end()) {
                (*writer)->write(stream, std::move(message));
            }
        }
    }
```

**Comment by achataigner** [comment]
Thank you guys ! Actually we use Kristoffer's tip: we don't declare any writer in our xml config file and it works fine !

**Comment by achataigner** [comment]
So this pull request can be canceled/closed

**Pull request closed without merging**
