### PR TITLE
add export for cloudbus_io

### PR DESCRIPTION
**Pull request by xueh2**
Add export/import for cloudbus_io functions.

### CODE REVIEW

**Comment by hansenms** [comment]
This is probably fine, but why is this needed now? Trying to understand the motivation.

**Comment by xueh2** [comment]
Try to link the gadgetron_toolbox_cloudbus in windows, sometimes visual studio complains about missing symbols of those functions in cloudbus_io.h.

**Comment by hansenms** [comment]
It has been linking fine until now, right? What is the change?

**Comment by xueh2** [comment]
Nothing in gadgetron. When trying to link the cloudbus toolbox lib outside gadgetron, sometimes visual studio encounters the missing symbol problems. Adding the windows dll export/import could make the linkage on a safer side.

**Comment by hansenms** [comment]
Problem is that the io part was deliberately made header only, so I am having a hard time seeing where this would come up. I can see problems with duplicate symbols maybe? But that could be solved by inlining.

Anyways, we can do this but it sort of follows the usual, I have no idea what is going on on Windows, so let's just move some code arround model. It's not particularly satisfying.

**Comment by xueh2** [comment]
Another option is to make those functions inline? This should solve the missing symbol problem as well.

**Comment by hansenms** [comment]
The reason why it was made header only was to avoid the exporting that struct with strings in, which also can cause problems on Windows. But if you have tested it, it's probably fine either way. You decide.

**Comment by hansenms** [comment]
@xueh2, do you want to merge this or should we inline?

**Comment by xueh2** [comment]
Let's merge this. I found inline solution can give duplicated symbol problem, if the cloud_io.h is included in multiple .cpp in a project.

**Pull request merged**
