### PR TITLE
Cleanup of Clang-deprecated function and comment blocks from code base

### PR DESCRIPTION
**Pull request by roopchansinghv**
Replace active instances of sprintf in codebase, with snprintf (as sprintf deprecated in current Clang versions).

Remove commented out blocks of code, also containing sprintf.

Trying with a differrent branch name - see if that was hanging the build pipeline ...

### CODE REVIEW

**Comment by roopchansinghv** [comment]
@hansenms - any thoughts as to why this particular build and testing pipeline is hanging?  Did I 'spam' Azure too much over [here](https://github.com/gadgetron/gadgetron/pull/1188/)?

**Comment by roopchansinghv** [comment]
Thanks @hansenms for getting the build running again.

I think the error with the conda build [here](https://dev.azure.com/microsoft-gadgetron/gadgetron-build/_build/results?buildId=992&view=logs&j=619d878d-a196-56ee-6058-ec2c5e5ba005&t=2ce36a30-ad51-5f78-2d60-5ce72b5a4f38&l=5798) is maybe coming from a HDF update?  These dependencies are in the main environment.yml, but not in conda/meta.yaml.  In the main environment file, h5py is at version 3.2.1, whereas when the conda package build occurs, h5py 3.3.0 is pulled in.  Should we try to pin to see if this is fixed?  I am not sure this issue is particular to the gadgetron build, but it 'just' popped up now.  And according to anaconda.org, [h5py 3.8 is now available](https://anaconda.org/conda-forge/h5py).

Thoughts welcome.

**Comment by hansenms** [comment]
@roopchansinghv yes, we should pin hdf5, I am surprised it doesn't follow from pulling in ismrmrd, but maybe we need to fix something there.

**Comment by roopchansinghv** [comment]
Okay - that 'took a minute' to work through.

Patch version has already been incremented to .6 - let me know if anything else is needed to approve this PR.

**Review by hansenms — APPROVED** [review]

**Pull request merged**
