### PR TITLE
Cloning considered unethical

### PR DESCRIPTION
**Pull request by dchansen**
This essential removes the clone function from the linearOperator class, and thus from virtually all operators. There are currently 0 instances of this function being used.

### CODE REVIEW

**Comment by hansenms** [comment]
Why is this a merge to master? And what exactly is "unethical"

**Comment by inati** [comment]
Could you rebate or something. You have a million commits.



Sent with a mobile device

-----Original Message-----

**Comment by hansenms** [comment]
@inati, this is a merge to master, which is wrong.

**Comment by dchansen** [comment]
Yeah sorry, my mistake. Redid with a new one. The unethical part was a silly attempt at a joke.

**Comment by hansenms** [comment]
You Danes and your strange sense of humor;)

**Pull request closed without merging**
