### PR TITLE
Added simple recon gadget that does fft+ssos and sends out image array. ...

### PR DESCRIPTION
**Pull request by inati**
... Changed default chains to use it.

### CODE REVIEW

**Comment by inati** [comment]
@hansenms, @gtdeveloper5, @dchansen, could you please take a look at this.  This is the simplest example of a "Recon Gadget" that takes an IsmrmrdReconData object in and puts an IsmrmrdImageArray out.

**Comment by hansenms** [comment]
Looks good to me. Do the test pass?

**Comment by inati** [comment]
There are only a few tests that use the default chain and they pass.



Sent with a mobile device

-----Original Message-----

**Comment by hansenms** [comment]
Feel free to merge when ready.

------

**Pull request merged**
