### PR TITLE
Change symbol to gadgetron 

### PR DESCRIPTION
**Pull request by gtdeveloper5**
Change symbol definition from "GT_" to "GADGETRON_"

### CODE REVIEW

**Comment by inati** [comment]
I think all these specific image tag things should be removed from the client.  The meta attribute string should be all you need.

**Comment by hansenms** [comment]
@inati , you should not have closed this. This does only concern the meta attribute string. @gtdeveloper5 can you send the request again.

**Comment by hansenms** [comment]
Let me clarify. @inati you were right to point out that this is an opportunity for cleanup in the client, but this should not have been just closed, since we need to discuss what is going on.

**Comment by inati** [comment]
Sorry that was an accident on a mobile phone web client.  Did not mean to close it.

**Comment by hansenms** [comment]
OK, it has been removed from the client, and now merged.

**Pull request closed without merging**
