### PR TITLE
install missing cmake files

### PR DESCRIPTION
**Pull request by xueh2**
install missing cmake files

### CODE REVIEW

**Comment by dchansen** [comment]
Honestly I don't think we should install any of the Find*.cmake files. Many of them have been superseded in newer versions of cmake and us installing them could break other installations.

Do you have something which breaks if we don't have the cmake files installed?

**Comment by xueh2** [comment]
It is mainly for package compiled on top of gadgetron, which can add gadgetron cmake module to help find packages.

**Comment by xueh2** [comment]
Can we merge this PR? Need it to move forward.

**Comment by dchansen** [comment]
No. I don't think we should. It will conflict with other projects that also want to install unrelated Find*.cmake modules, as well as the native CMake modules themselves.

Anything that links to Gadgetron via CMake should (in theory) get all the dependencies automatically. If that doesn't happen, we should modify [gadgetron-config](cmake/gadgetron-config.cmake.in) to correctly expose the libraries we require.

**Pull request closed without merging**
