### PR TITLE
Update README (bootstrap conda no longer needed)

### PR DESCRIPTION
**Pull request by hansenms**
We no longer need to bootstrap the conda environment to install other dependencies since they are all being provided by conda (or pip). This PR updates the README.md file to reflect that.

### CODE REVIEW

**Review by roopchansinghv — CHANGES_REQUESTED** [review]
When installing Gadgetron via Conda environment, the user won't get source code.

At the top of the "Building in the conda environment section", you probably want to add a command or set of commands to clone the Gadgetron's "origin" Git repository, going to the cloned repository locally, then setting up the local build.

I should have sent the recommended changes to you.

**Comment by hansenms** [comment]
@roopchansinghv looks like you have already push that change? Is there another change you are requesting?

**Comment by roopchansinghv** [comment]
Wasn't clear from the workflow that my suggested changes showed up in the PR after I pushed back to your branch.  Will go ahead, approve, and close this.

**Review by roopchansinghv — APPROVED** [review]

**Comment by hansenms** [comment]
@roopchansinghv thanks. Workflow is a bit confusing.

**Pull request merged**
